IBM/operand-deployment-lifecycle-manager

- OWNERS
@gyliu513 
Add @jinchun-dev (interns in the installer) as owners. Then we can review each other to add tests and optimize the controller in the next week.
> Add Jin into OWNERS

- Makefile
- common/config/.yamllint.yml
- common/scripts/push-csv.sh
issue: https://github.com/IBM/common-service-operator/issues/9
> Push csv to quay.io

- deploy/crds/operator.ibm.com_metaoperators_crd.yaml
- deploy/crds/operator.ibm.com_v1alpha1_metaoperator_cr.yaml
- deploy/olm-catalog/common-service-operator/0.0.3/common-service-operator.v0.0.3.clusterserviceversion.yaml
- deploy/olm-catalog/common-service-operator/0.0.3/operator.ibm.com_metaoperators_crd.yaml
- docs/install.md
- pkg/apis/operator/v1alpha1/metaoperator_types.go
https://github.com/IBM/common-service-operator/issues/11
> Update install readme

- docs/install_on_kubernetes.md
> Add an example for installing common service operator on k8s

- docs/install.md
- docs/install_on_kubernetes.md
- pkg/controller/metaoperatorcatalog/metaoperatorcatalog_controller.go
- pkg/controller/metaoperatorset/metaoperatorset_controller.go
- pkg/controller/metaoperatorset/reconcile_metaoperatorcatalog.go
- pkg/util/merge.go
This is the follow up of rename from common service operator to meta operator, hope this PR is the last PR about this rename.
/cc @horis233 @DanielXLee @gyliu513
> minor fix on rename to meta-operator

- pkg/controller/metaoperatorset/metaoperatorset_controller.go
> improve wait for function for subscriptions.

- Makefile
> fix makefile issue

- deploy/olm-catalog/meta-operator/0.0.1/meta-operator.v0.0.1.clusterserviceversion.yaml
> Pass operator-courier verify

- build/Dockerfile
- build/Dockerfile.ppc64le
- build/Dockerfile.s390x
> Add licenses in image

- pkg/controller/metaoperatorcatalog/metaoperatorcatalog_controller.go
- pkg/controller/metaoperatorcatalog/metaoperatorcatalog_controller_test.go
Fixed: https://github.com/IBM/meta-operator/issues/60
> Add unit test for meta operator catalog controller

- common/Makefile.common.mk
- deploy/crds/operator.ibm.com_metaoperatorcatalogs_crd.yaml
- deploy/olm-catalog/meta-operator/0.0.1/operator.ibm.com_metaoperatorcatalogs_crd.yaml
- docs/install/common-service-integration.md
- docs/install/install-with-kind.md
- docs/install/install.md
- pkg/apis/operator/v1alpha1/metaoperatorcatalog_types.go
> Add Description for catalog

- pkg/controller/metaoperatorset/reconcile_metaoperatorcatalog.go
> Watch CatalogSource and CatalogSourceNamespace

- pkg/controller/metaoperatorconfig/metaoperatorconfig_controller_test.go
> add unit test for config

- deploy/crds/operator.ibm.com_metaoperatorsets_crd.yaml
- deploy/crds/operator.ibm.com_v1alpha1_metaoperatorcatalog_cr.yaml
- deploy/crds/operator.ibm.com_v1alpha1_metaoperatorconfig_cr.yaml
- deploy/crds/operator.ibm.com_v1alpha1_metaoperatorset_cr.yaml
- deploy/olm-catalog/meta-operator/0.0.1/meta-operator.v0.0.1.clusterserviceversion.yaml
- deploy/olm-catalog/meta-operator/0.0.1/operator.ibm.com_metaoperatorsets_crd.yaml
- deploy/role.yaml
- pkg/apis/operator/v1alpha1/metaoperatorset_types.go
Remove placeholder operator jenkin and etcd.
> remove placeholder operators

- deploy/operator.yaml
- pkg/controller/metaoperatorcatalog/metaoperatorcatalog_controller.go
- pkg/controller/metaoperatorconfig/metaoperatorconfig_controller.go
- pkg/util/seed_cr.go
fixes https://github.com/IBM/meta-operator/issues/50
/cc @gyliu513 @DanielXLee @horis233
> enable multi-ns for meta-operator

- OWNERS
> Adding Shikha to OWNER

- deploy/crds/operator.ibm.com_v1alpha1_metaoperatorset_cr.yaml
- deploy/olm-catalog/meta-operator/0.0.1/meta-operator.v0.0.1.clusterserviceversion.yaml
- deploy/role.yaml
* Add more permission to meta-operator
* Add the core operators as placeholder
/cc @gyliu513 @DanielXLee @horis233
> fix permission issue and add placeholder to main operators

- deploy/crds/operator.ibm.com_metaoperatorsets_crd.yaml
- deploy/crds/operator.ibm.com_v1alpha1_metaoperatorset_cr.yaml
- deploy/olm-catalog/meta-operator/0.0.1/meta-operator.v0.0.1.clusterserviceversion.yaml
- deploy/olm-catalog/meta-operator/0.0.1/operator.ibm.com_metaoperatorsets_crd.yaml
- go.mod
- go.sum
- pkg/apis/operator/v1alpha1/metaoperatorset_types.go
- pkg/controller/metaoperatorset/metaoperatorset_controller_test.go
Fixed: https://github.com/IBM/meta-operator/issues/71
> Remove description from set api

- deploy/crds/operator.ibm.com_v1alpha1_metaoperatorcatalog_cr.yaml
- deploy/olm-catalog/meta-operator/0.0.1/meta-operator.v0.0.1.clusterserviceversion.yaml
- docs/install/common-service-integration.md
> use ibm-common-services namespace

- common/config/.golangci.yml
- pkg/controller/metaoperatorset/metaoperatorset_controller.go
- pkg/controller/metaoperatorset/metaoperatorset_controller_test.go
> Ensure only one metaoperatorconfig and metaoperatorcatalog in one namespace

- deploy/crds/operator.ibm.com_v1alpha1_metaoperatorcatalog_cr.yaml
- deploy/crds/operator.ibm.com_v1alpha1_metaoperatorconfig_cr.yaml
- deploy/crds/operator.ibm.com_v1alpha1_metaoperatorset_cr.yaml
- deploy/olm-catalog/meta-operator/0.0.1/meta-operator.v0.0.1.clusterserviceversion.yaml
https://github.com/IBM/ibm-auditlogging-operator
> Onboard auditlogging-operator with meta-operator

- deploy/role_binding.yaml
- pkg/controller/metaoperatorset/metaoperatorset_controller.go
- pkg/util/seed_cr.go
Fixes 
1. fix the error when there are no metaoperatorconfig and metaoperatorcatalog instances
2. update meta-operator name to ibm-common-services namespace
```release-note
NONE
```
> update namespace and list check

- Makefile
- README.md
1) update the README by updating the namespace.
2) Update the Makefile to ignore the not founded resources.
```release-note
```
> README and Makefile

- Makefile
- build/Dockerfile
- build/Dockerfile.ppc64le
- build/Dockerfile.s390x
- deploy/operator.yaml
Fixes #119
```release-note
```
> Update image name to odlm

- test/helpers/helpers.go
make test failed due to the csv of etcd and jenkins can not be installed success, create the operator group for this 2 csv under their namespace to pass the test.
```release-note
```
> create operator group for test csv

- pkg/apis/operator/v1alpha1/zz_generated.openapi.go
- pkg/controller/operandconfig/operandconfig_controller.go
- pkg/controller/operandconfig/operandconfig_controller_test.go
- pkg/controller/operandregistry/operandregistry_controller.go
- pkg/controller/operandrequest/operandrequest_controller.go
> Update config controller seed cr file name

- .osdk-scorecard.yaml
- build/bin/entrypoint
- cmd/manager/main.go
- common/Makefile.common.mk
- common/scripts/push-csv.sh
- docs/install/common-service-integration.md
- docs/install/install-with-kind.md
- docs/install/install.md
- pkg/controller/operandconfig/operandconfig_controller_test.go
- pkg/controller/operandregistry/operandregistry_controller_test.go
- pkg/controller/operandrequest/operandrequest_controller_test.go
- pkg/controller/operandrequest/reconcile_operator.go
- test/e2e/operandrequest_test.go
- test/helpers/helpers.go
Fixes #
/cc @chenzhiwei @DanielXLee @horis233 
```release-note
NONE
```
> Some clean up for meta-operator to ODLM

- deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
- deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
- deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
For on board catalog operator
https://github.com/IBM/ibm-catalog-operator
Fixes #
```release-note
```
> onboarding catalog operator

- README.md
- docs/install/common-service-integration.md
- docs/install/install-with-kind.md
- docs/install/install.md
- test/config/constants.go
- test/helpers/helpers.go
- test/testgroups/commonservice.go
Fixes #
/cc @chenzhiwei @DanielXLee @horis233 
```release-note
NONE
```
> Do not use meta operator concept.

- docs/install/common-service-integration.md
- docs/install/install.md
- test/config/constants.go
- test/e2e/operandrequest_test.go
- test/helpers/helpers.go
- test/testgroups/commonservice.go
- test/testsuits/operandrequest.go
Fixes #
/cc @chenzhiwei @DanielXLee @horis233 
```release-note
```
> Clean up for odlm concept

- deploy/crds/operator.ibm.com_operandrequests_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandrequests_crd.yaml
- pkg/apis/operator/v1alpha1/operandrequest_types.go
- pkg/controller/operandrequest/operandrequest_controller.go
- pkg/controller/operandrequest/operandrequest_controller_test.go
- pkg/controller/operandrequest/reconcile_operand.go
- pkg/controller/operandrequest/reconcile_operator.go
- pkg/controller/operandrequest/request_status.go
Fixes #145
```release-note
```
> Enhance operand request condition status

- deploy/crds/operator.ibm.com_operandregistries_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandregistries_crd.yaml
- go.sum
- pkg/apis/operator/v1alpha1/operandregistry_types.go
Fixes #144
```release-note
```
> Add scope for operand registry crd

- deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
- deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
- deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
Onboarding Cloudctl / Platform API operator
https://github.com/IBM/ibm-platform-api-operator
Fixes #
```release-note
```
> onboarding platform-api

- pkg/apis/operator/v1alpha1/operandregistry_types.go
- pkg/controller/operandregistry/operandregistry_controller.go
Fixes #149
```release-note
```
> Set default value for OperandRegistry

- deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
- deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
- deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
Onboarding Helm based operators for helm-repo, helm-api and management repo components
- Git repos
https://github.com/IBM/ibm-management-repo-operator
https://github.com/IBM/ibm-helm-repo-operator
https://github.com/IBM/ibm-helm-api-operator
- CSV for all the three operators has been pushed to quay.io
Fixes #
```release-note
```
> Onboard helm api, helm repo, management repo components

- docs/install/common-service-integration.md
Fixes #
```release-note
NONE
```
> remove `required` section for dependency from onboard document

- common/config/.golangci.yml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
- pkg/apis/operator/v1alpha1/operandrequest_types.go
- pkg/controller/operandrequest/reconcile_operator.go
- pkg/controller/operandrequest/request_status.go
Fixes #152
```release-note
```
> Add operand status in members and fix delete status issue

- deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
- deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
- deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
This PR integrates Exporter operator of IBM Monitoring stack into ODLM.
No. This PR does not change any image version.
```release-note
NONE
```
> Integrate Exporter operator of IBM Monitoring stack

- Makefile
- pkg/apis/operator/v1alpha1/operandconfig_types.go
- pkg/apis/operator/v1alpha1/operandregistry_types.go
- pkg/controller/operandrequest/operandrequest_controller.go
- pkg/controller/operandrequest/request_status.go
Fixes #143
```release-note
```
> Support create operand request in another namespace

- docs/design/operand-deployment-lifecycle-manager.md
Fixes #
/cc @chenzhiwei @DanielXLee @horis233 
```release-note
NONE
```
> Added upgrade section.

- README.md
Fixes #
```release-note
NONE
```
> Link to design in README

- common/scripts/push-csv.sh
> Enhance push csv script to support update csv

- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
- go.mod
- go.sum
- pkg/apis/operator/v1alpha1/operandregistry_types.go
- pkg/controller/operandrequest/operandrequest_controller.go
- pkg/controller/operandrequest/reconcile_operand.go
- pkg/controller/operandrequest/reconcile_operator.go
> Support delete specific operator

- pkg/apis/operator/v1alpha1/operandconfig_types.go
- pkg/apis/operator/v1alpha1/operandregistry_types.go
- pkg/apis/operator/v1alpha1/operandrequest_types.go
- pkg/controller/operandregistry/operandregistry_controller.go
- pkg/controller/operandrequest/operandrequest_controller.go
Update comments and remove unused code
```release-note
NONE
```
> complete comments and remove registry list

- build/Dockerfile
- build/Dockerfile.ppc64le
- build/Dockerfile.s390x
Fixes #
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/36239
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/36238
```release-note
NONE
```
> Update ubi version

- cmd/manager/main.go
- pkg/apis/operator/v1alpha1/operandconfig_types.go
- pkg/controller/operandconfig/operandconfig_controller.go
- pkg/controller/operandregistry/operandregistry_controller.go
- pkg/controller/operandrequest/config_status.go
- pkg/controller/operandrequest/operandrequest_controller.go
- pkg/controller/operandrequest/operandrequest_controller_test.go
- pkg/controller/operandrequest/reconcile_operand.go
- pkg/controller/operandrequest/reconcile_operator.go
- pkg/controller/operandrequest/request_status.go
- pkg/util/merge.go
- pkg/util/seed_cr.go
Fixes #170 #164 
- format logs template.
- enhance request member status update
- remove listconfig function to get operandconfig. 
```release-note
NONE
```
> Enhance request member status update

- build/Dockerfile
- build/Dockerfile.ppc64le
- build/Dockerfile.s390x
Fixes #
We need to use the image digest instead of the image tag.
```release-note
NONE
```
> using digest to replace tag

- pkg/controller/operandrequest/reconcile_operator.go
Fixes #180 
```release-note
```
> Add check logic before delete subscription

- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
- deploy/operator.yaml
> Add label for health check

- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
- deploy/operator.yaml
- pkg/controller/operandrequest/config_status.go
- pkg/controller/operandrequest/registry_status.go
- pkg/controller/operandrequest/request_status.go
Fixes #185 
- fix deployment log level
- add logs for status update
```release-note
NONE
```
> Enhance OperandRequest status update

- docs/install/install-with-ocp-3.11.md
- docs/install/install.md
Fixes #
Separate install document to 4.2+ and 3.11
```release-note
NONE
```
> Separate install doc

- deploy/crds/operator.ibm.com_operandregistries_crd.yaml
- deploy/crds/operator.ibm.com_operandrequests_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandregistries_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandrequests_crd.yaml
- pkg/apis/operator/v1alpha1/operandregistry_types.go
- pkg/apis/operator/v1alpha1/operandrequest_types.go
Fixes #171
```release-note
```
> Add optional annotation and description

- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
- deploy/operator.yaml
This ensures Metering, Licensing and Healthcheck can monitor the pods.
> add metering annotation

- deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
- deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
- deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
Updates for helm squad operators
Fixes #
```release-note
```
> update helm squad operators

- deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
- deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
- deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
This PR integrates IBM Grafana operator which is important for IBM Monitoring service.
Fixes # N/A
```release-note
NONE
```
> onboard grafana operator

- pkg/controller/operandrequest/request_status.go
For different request show different member
Fixes #
```release-note
```
> Enhance operandrequest member status

- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
- deploy/operator.yaml
- pkg/controller/operandconfig/operandconfig_controller.go
- pkg/controller/operandregistry/operandregistry_controller.go
- pkg/controller/operandrequest/operandrequest_controller.go
- pkg/controller/operandrequest/reconcile_operand.go
- pkg/controller/operandrequest/reconcile_operator.go
- pkg/util/seed_cr.go
Fixes #208 
Adjust log level to decrease flooding logs
In order to avoid conflict, the log level changes for operand in #207 
```release-note
NONE
```
> Adjust logs level

- deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
- deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
- deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
- docs/install/install-with-kind.md
- docs/install/install-with-ocp-3.11.md
- docs/install/install.md
remove management repo operator
Fixes #
```release-note
```
> remove unused management repo operator

- pkg/controller/operandrequest/operandrequest_controller.go
Fixes #214 
Check if there are subscriptions with label "operator.ibm.com/opreq-control". If there is no subscription, remove the finalizer.  
```release-note
NONE
```
> Update finalizer check

- pkg/controller/operandrequest/config_status.go
Fixes #212 
When ODLM updates the operand status, get the last instance first then update operand status.
```release-note
NONE
```
> get the config before update

- pkg/apis/operator/v1alpha1/operandconfig_types.go
- pkg/controller/operandrequest/config_status.go
- pkg/controller/operandrequest/operandrequest_controller.go
- pkg/controller/operandrequest/request_status.go
Fixes #218
```release-note
```
> Fix cluster phase display incorrect issue

- deploy/crds/operator.ibm.com_operandconfigs_crd.yaml
- deploy/crds/operator.ibm.com_operandregistries_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandconfigs_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operator.ibm.com_operandregistries_crd.yaml
- pkg/apis/operator/v1alpha1/operandconfig_types.go
- pkg/apis/operator/v1alpha1/operandregistry_types.go
- pkg/apis/operator/v1alpha1/operandrequest_types.go
- pkg/controller/operandrequest/config_status.go
- pkg/controller/operandrequest/operandrequest_controller.go
- Add phase to `operandConfig`  and `operandRegistry` status
- Initialize the status for `operandRequest` instance
```release-note
NONE
```
> Add phase to config and registry status

- Makefile
- pkg/apis/operator/v1alpha1/operandrequest_types.go
- pkg/controller/operandrequest/operandrequest_controller.go
Remove the Initializing log, for multi-reconcile, this log will cause confusion.
Fixes #
```release-note
```
> Remove confuse init log

- pkg/apis/operator/v1alpha1/operandrequest_types.go
- pkg/controller/operandrequest/reconcile_operator.go
1. Update condition status to false when sub, csv create/update/delete failed
2. Add not found condition for the subscription not find from the request registry
Fixes #
```release-note
```
> Enhance OperandRequest condition

- pkg/apis/operator/v1alpha1/operandconfig_types.go
- pkg/controller/operandrequest/config_status.go
Fixes #230 
```release-note
```
> Fix service status update issue

- pkg/controller/operandconfig/operandconfig_controller_test.go
- pkg/controller/operandregistry/operandregistry_controller_test.go
- pkg/controller/operandrequest/operandrequest_controller_test.go
1. Add assert check for sub and csv number
2. Remove init status to cover code init status logic
Like this issue: https://github.com/IBM/operand-deployment-lifecycle-manager/issues/230
unit test will find it.
Fixes #
```release-note
```
> Update unit test

- README.md
Just add a state bar for the README file
Fixes #
```release-note
```
> Add image, go and license state on README

- deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
Set management ingress operator enabled by default.
```release-note
NONE
```
> Update OperandRequest CR  

- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
- docs/design/operand-deployment-lifecycle-manager.md
Add a detailed description into the CSV, which will be shown in the OCP operatorhub.
Contents are from the ODLM design document and installation document.
preview from [operatorhub](https://operatorhub.io/preview) 
```release-note
NONE
```
> Update odlm csv description

- deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
Enable common ui by default
```release-note
NONE
```
> Enable common ui

- common/scripts/codecov.sh
Remove codecov upload token from source code.
I have regenerated a new token and put it in a secret so that codecov job can access it.
Fixes #
```release-note
```
> remove codecov upload token from source

- docs/design/operand-deployment-lifecycle-manager.md
> fix typo in design doc

- common/config/.golangci.yml
- go.mod
- go.sum
- pkg/controller/operandrequest/operandrequest_controller_test.go
Enhance e2e test:
- Add OperandConfig Update
- Verify the generated custom resource  
```release-note
NONE
```
> Enhance e2e test

- README.md
- docs/design/operand-deployment-lifecycle-manager.md
This PR adds introduction for CRD short names as a table in the README.md and the design document.
Fixes #246 
```release-note
NONE
```
> Add introduction for CRD short names

- docs/install/install.md
Add grafana and prometheus operators to the list.
```
- name: ibm-monitoring-grafana-operator
- name: prometheus-operator
```
It is confusing others without the two operators as many people are using this list for test.
Fixes #
```release-note
NO
```
> Update operator list

- deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
This PR updates channels of monitoring operators from alpha to stable-v1
Fixes #
```release-note
None
```
> update channel for monitoring operators

- deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
For Common Services 3.3.0 release need to move to stable-v1
channel.
Fixes #
```release-note
```
> Change channel of ingress operator to stable

- deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
For Common Services 3.3.0 release needs to move to stable-v1 channel.
> change channel of auditlogging operator to stable

- deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
For Common Services 3.3.0 release need to move to stable-v1
Fixes #
```release-note
```
> Update mongo channel

- .osdk-scorecard.yaml
- Makefile
- common/scripts/multiarch_image.sh
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operator.ibm.com_operandconfigs_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operator.ibm.com_operandregistries_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operator.ibm.com_operandrequests_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/operand-deployment-lifecycle-manager.package.yaml
- deploy/operator.yaml
- docs/install/common-service-integration.md
- version/version.go
Bump ODLM operator CSV version to v1.1.0
Bump ODLM operator image version to 1.1.0
Bump ODLM operator channel version to stable-v1
Fixes #253 
@chenzhiwei @DanielXLee 
Do we need to keep version `0.0.1` in the `deploy` folder? or Do we need to create a stable branch for version `0.0.1`?
```release-note
NONE
```
> Update ODLM version to 1.1.0

- deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
> change metering channel to stable-v3

- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
1. Move some description from 0.0.1 to here
2. Remove prometheus-operator form new csv
Fixes #
```release-note
```
> Update new csv

- docs/install/install.md
This is a follow up to this PR https://github.com/IBM/operand-deployment-lifecycle-manager/pull/259
Fixes #
```release-note
None
```
> Remove prometheus-operator from list

- deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
update healthcheck channel to stable-v1
Fixes #
```release-note
```
> update healthcheck channel

- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
> Update csv maturity to stable

- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
- deploy/operator.yaml
> Use latest tag now

- deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
- deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
update channel for helm operators
Fixes #
```release-note
```
> update channel for helm operators

- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
> Update logging csv channel

- deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
Update licensing olm channel
Fixes #
```release-note
```
> update licensing channel

- deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
> change metering channel to stable-v1

- deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
Fixes #
```release-note
NONE
```
> update cert-manager channel

- deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
Fixes #
```release-note
NONE
```
> Update iam and commonui channel

- README.md
- docs/design/operand-deployment-lifecycle-manager.md
Fixes #273 
```release-note
NONE
```
> Update readme to follow common service template

- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
- deploy/operator.yaml
Fixes #
Update ODLM image version
```release-note
NONE
```
> update ODLM operator image version

- .osdk-scorecard.yaml
- Makefile
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operator.ibm.com_operandconfigs_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operator.ibm.com_operandregistries_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operator.ibm.com_operandrequests_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/operand-deployment-lifecycle-manager.package.yaml
- deploy/operator.yaml
- docs/install/common-service-integration.md
- version/version.go
- bump version to 1.2.0
- Enable multi namespaces and all namespaces install mode
Fixes #284 
```release-note
Enable multi namespaces and all namespaces install mode
```
> bump version to 1.2.0

- pkg/apis/operator/v1alpha1/operandrequest_types.go
- pkg/controller/operandrequest/operandrequest_controller.go
Add ready condition status for operators and operands.
Fixes #290 
```release-note
NONE
```
> Add Ready status for condition status

- common/config/.golangci.yml
- pkg/controller/operandbindinfo/operandbindinfo_controller.go
- pkg/controller/operandbindinfo/operandbindinfo_controller_test.go
Add unit test for OperandBindInfo
Fixes #295 
```release-note
NONE
```
> Add unit test for OperandBindInfo

- README.md
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
- docs/design/operand-deployment-lifecycle-manager.md
- Add OperandBindInfo into README
- Add OperandBindInfo into the design doc
- Add OperandBindInfo into CSV description
```release-note
NONE
```
> Add OperandBindInfo into document and README

- pkg/controller/operandrequest/reconcile_operand.go
This PR is for the uninstall of Operator dependency management.
When OperandRquest instance is created by ODLM, the OperandRquest and the Operator and Operands won't be uninstalled when their parent OperandRequest is removed.
Thus, this PR adds CSV as the owner of the generated OperandRquest instance. When the operator CSV is uninstalled, the generated OperandRquest will be removed as well.
Refer #279
```release-note
NONE
```
> Set csv as the owner of the operandrequest instance

- pkg/controller/operandbindinfo/operandbindinfo_controller.go
OprandRegistry has provided a method to get Operator, replace the loop logic with OperandRegistry API method
Fixes #
```release-note
```
> Enhance bindinfo obtain namespace logic

- deploy/crds/operator.ibm.com_operandbindinfos_crd.yaml
- deploy/crds/operator.ibm.com_operandconfigs_crd.yaml
- deploy/crds/operator.ibm.com_operandregistries_crd.yaml
- deploy/crds/operator.ibm.com_operandrequests_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operator.ibm.com_operandbindinfos_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operator.ibm.com_operandconfigs_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operator.ibm.com_operandregistries_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operator.ibm.com_operandrequests_crd.yaml
- pkg/apis/operator/v1alpha1/operandbindinfo_types.go
- pkg/apis/operator/v1alpha1/operandconfig_types.go
- pkg/apis/operator/v1alpha1/operandregistry_types.go
- pkg/apis/operator/v1alpha1/operandrequest_types.go
Fixes #305 
```release-note
```
> Add print column for 4 crds

- pkg/controller/operandrequest/reconcile_operand.go
- This PR to revert the controller added to the `OperandRequest` instance generated by ODLM 
- ODLM doesn't need to wait for the uninstall `OperandRequest` instance. Otherwise, it will cause a deadlock until the timeout.
```release-note
NONE
```
> Enhance uninstall

- pkg/apis/operator/v1alpha1/operandbindinfo_types.go
- pkg/apis/operator/v1alpha1/operandrequest_types.go
- pkg/controller/operandconfig/operandconfig_controller.go
- pkg/controller/operandconfig/operandconfig_controller_test.go
- pkg/controller/operandregistry/operandregistry_controller.go
- pkg/controller/operandregistry/operandregistry_controller_test.go
- pkg/controller/operandrequest/operandrequest_controller.go
Fixes #321 #322 #314 
```release-note
```
> Enhance registry controller to trigger request reconcile

- deploy/operator.yaml
Fixes #326 
```release-note
```
> Use latest image tag when development phase

- cmd/manager/main.go
> Remove useless code from main.go

- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
> Update image version in csv

- pkg/apis/operator/v1alpha1/operandbindinfo_types.go
- pkg/apis/operator/v1alpha1/operandrequest_types.go
1. Fix add lable for operandrequest and operandbindinfo
Fixes #329 
```release-note
```
> Fix add label issue

- pkg/controller/operandbindinfo/operandbindinfo_controller.go
1. Fix copy config map issue
2. Add more event for this controller
3. Remove some variables for more readable
Fixes #331 
```release-note
```
> Fix copy config map issue

- pkg/controller/operandbindinfo/operandbindinfo_controller.go
Fixes #335
```release-note
```
> Add prefix for the copied cm and secret

- common/scripts/multiarch_image.sh
- deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
remove navconfiguration: {}
Fixes #
```release-note
```
> remove navconfiguration: {}

- test/config/constants.go
- test/e2e/odlm_test.go
- test/helpers/helpers.go
- test/testgroups/operandbindinfo_group.go
- test/testgroups/operandconfig_group.go
- test/testgroups/operandregistry_group.go
- test/testgroups/operandrequest_group.go
Fixes #346 
```release-note
```
> Add more case assert for e2e

- pkg/apis/operator/v1alpha1/operandbindinfo_types.go
- pkg/apis/operator/v1alpha1/operandrequest_types.go
This PR is used to append label when the OperandRequest an OperandBindInfo have existing labels
Fixes #351 
```release-note
NONE
```
> append label and remove the label for the same function

- Makefile
- cmd/manager/main.go
- deploy/role_binding.yaml
- test/config/constants.go
- test/helpers/helpers.go
- test/testgroups/operandbindinfo_group.go
- test/testgroups/operandconfig_group.go
- test/testgroups/operandregistry_group.go
- test/testgroups/operandrequest_group.go
> Fix e2e test issue

- docs/dev/e2e.md
- test/helpers/helpers.go
- test/testgroups/operandbindinfo_group.go
- test/testgroups/operandrequest_group.go
- Fix operand absent and present
- Update operandBindInfo e2e test
```release-note
NONE
```
> Update end to end test

- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
> Update csv describe with jenkins example

- docs/install/install.md
Upgrade operator docs moved from /design to /user but docs have not been changed.
> fix the wrong path issue

- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
- deploy/operator.yaml
Bump metering version to 3.4.0
```release-note
NONE
```
> Bump metering version to 3.4.0

- pkg/controller/operandbindinfo/operandbindinfo_controller.go
- pkg/controller/operandconfig/operandconfig_controller.go
- pkg/controller/operandregistry/operandregistry_controller.go
- pkg/controller/operandrequest/operandrequest_controller.go
- pkg/controller/operandrequest/reconcile_operand.go
- pkg/controller/operandrequest/reconcile_operator.go
- Supplement logs
- Fix typo and updating existing logs
```release-note
NONE
```
> Update log messages

- README.md
- deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
- deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
- deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
- deploy/operator.yaml
> Fix cv lint error

- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
- deploy/operator.yaml
> Update the images tag to digest

- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
- deploy/operator.yaml
> Revert to use image tag

- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/operand-deployment-lifecycle-manager.package.yaml
- deploy/operator.yaml
- Create a beta channel
- Update tag to digest 
```release-note
create the beta channel
```
> create beta channel and update tag to digest 

- Makefile
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.1/operand-deployment-lifecycle-manager.v1.2.1.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.1/operator.ibm.com_operandbindinfos_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.1/operator.ibm.com_operandconfigs_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.1/operator.ibm.com_operandregistries_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.1/operator.ibm.com_operandrequests_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/operand-deployment-lifecycle-manager.package.yaml
- version/version.go
Fixes #
```release-note
Bump version 1.2.1
```
> Bump version to 1.2.1

- Makefile
@chenzhiwei @DanielXLee 
Inject VCS info to the docker image
```release-note
NONE
```
> inject vcs info to docker image

- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.1/operator.ibm.com_operandregistries_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.1/operator.ibm.com_operandrequests_crd.yaml
Fixes #
```release-note
NONE
```
> Using 1.2.0 crds for 1.2.1

- Makefile
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.1/operand-deployment-lifecycle-manager.v1.2.1.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.2/operand-deployment-lifecycle-manager.v1.2.2.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.2/operator.ibm.com_operandbindinfos_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.2/operator.ibm.com_operandconfigs_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.2/operator.ibm.com_operandregistries_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.2/operator.ibm.com_operandrequests_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/operand-deployment-lifecycle-manager.package.yaml
This PR id for pushing 1.2.1  version odlm to the beta channel.
https://quay.io/repository/opencloudio/odlm/manifest/sha256:91b184b7dce5a4f91a450d25d3c21cf2da1bb44a23f83ad318dcae576aff6da4
```release-note
NONE
```
> Push 1.2.1 to the beta channel

- deploy/olm-catalog/operand-deployment-lifecycle-manager/operand-deployment-lifecycle-manager.package.yaml
Bump stable-v1 channel to use the csv 1.2.1
```release-note
```
> bump stablev-1 channel to use CSV 1.2.1

- go.mod
- go.sum
/kind bug
fixes https://github.com/IBM/operand-deployment-lifecycle-manager/issues/401
/cc @gyliu513
> remove package dependency bou.ke/monkey

- pkg/controller/operandrequest/reconcile_operator.go
Fixes #421 
```release-note
```
> enhance delete subscription

- pkg/apis/operator/v1alpha1/operandregistry_types.go
- pkg/controller/operandconfig/operandconfig_controller.go
- pkg/controller/operandregistry/operandregistry_controller.go
- pkg/controller/operandrequest/operandrequest_controller.go
Fixes #411
```release-note
```
> Watch OperandRegisty spec change in OperandRequest controller

- pkg/apis/operator/v1alpha1/operandrequest_types.go
- pkg/controller/operandregistry/operandregistry_controller.go
Fixes #414
```release-note
```
> Watch OperandRequest status change in OperandRegistry controller

- pkg/controller/operandrequest/reconcile_operand.go
Fixes #422
```release-note
```
> Fix make check error SA5011: possible nil pointer dereference

- pkg/controller/operandrequest/reconcile_operand.go
Delete status for OperandRequest cr in the OperandConfig
Fixes #406 
```release-note
NONE
```
> Cleanup OperandConfig status

- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.2/operand-deployment-lifecycle-manager.v1.2.2.clusterserviceversion.yaml
- deploy/operator.yaml
- docs/design/operand-deployment-lifecycle-manager.md
- Update operator csv descriptions to use Jenkins as an example
- Update design docs to use Jenkins as an example
- Fix typos in the docs
- Using the latest image in the operator.yaml file
Fixes #
```release-note
NONE
```
> Update documents using jenkins as example

- pkg/controller/operandrequest/operandrequest_controller.go
This PR enhances the logic for the finalizer management. 
Add `ensureFinalizer` function to make sure the specific finalizer exists.
Add `removeFinalizer` function to remove a specific finalizer.
Therefore, we can keep existing finalizers added by end-users.
Fixes #431
```release-note
```
> Update finializer management

- pkg/controller/operandregistry/operandregistry_controller.go
1. Add comments for the status update
2. Don't reconcile when OperandRegistry status updates
Fixes #436 
```release-note
```
> Add comments and only wtach operandregistry changing

- pkg/apis/operator/v1alpha1/operandrequest_types.go
- pkg/controller/operandrequest/reconcile_operator.go
Fixes #439
```release-note
```
> Fresh member status

- pkg/apis/operator/v1alpha1/operandbindinfo_types.go
- pkg/apis/operator/v1alpha1/operandconfig_types.go
- pkg/apis/operator/v1alpha1/operandregistry_types.go
- pkg/apis/operator/v1alpha1/operandrequest_types.go
- pkg/controller/operandbindinfo/operandbindinfo_controller.go
- pkg/controller/operandconfig/operandconfig_controller.go
- pkg/controller/operandregistry/operandregistry_controller.go
- pkg/controller/operandregistry/operandregistry_controller_test.go
- pkg/controller/operandrequest/config_status.go
- pkg/controller/operandrequest/operandrequest_controller.go
- pkg/controller/operandrequest/operandrequest_controller_test.go
- pkg/controller/operandrequest/reconcile_operand.go
- pkg/controller/operandrequest/reconcile_operator.go
Fixes #430
```release-note
```
> Enhance default value to reduce k8s api call

- pkg/apis/operator/v1alpha1/operandregistry_types.go
- pkg/apis/operator/v1alpha1/operandrequest_types.go
- pkg/controller/common/fetch.go
- pkg/controller/operandconfig/operandconfig_controller.go
- pkg/controller/operandregistry/operandregistry_controller.go
- pkg/controller/operandrequest/config_status.go
- pkg/controller/operandrequest/operandrequest_controller.go
- pkg/controller/operandrequest/operandrequest_controller_test.go
- pkg/controller/operandrequest/reconcile_operand.go
- pkg/controller/operandrequest/reconcile_operator.go
Fixes #450 
```release-note
```
> Move all the default value set into the fetch method

- pkg/apis/operator/v1alpha1/operandregistry_types.go
- pkg/apis/operator/v1alpha1/operandrequest_types.go
- pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
- pkg/controller/operandbindinfo/operandbindinfo_controller.go
- pkg/controller/operandregistry/operandregistry_controller.go
- pkg/controller/operandregistry/operandregistry_controller_test.go
- pkg/controller/operandrequest/operandrequest_controller.go
- pkg/controller/operandrequest/reconcile_operand.go
- pkg/controller/operandrequest/reconcile_operator.go
Fixes #448
```release-note
```
> Check catalog source status

- pkg/apis/operator/v1alpha1/operandrequest_types.go
Fixes #453 
```release-note
```
> Fix fresh member status issue

- pkg/controller/operandbindinfo/operandbindinfo_controller.go
- pkg/controller/operandrequest/operandrequest_controller.go
- pkg/controller/operandrequest/reconcile_operand.go
- pkg/controller/operandrequest/reconcile_operator.go
1. Remove excess cr update method to solve cr update conflict issue
2. Update some log message
Related to #455
```release-note
```
> Remove excess cr update

- pkg/controller/operandregistry/operandregistry_controller_test.go
- pkg/controller/operandrequest/operandrequest_controller_test.go
> Enable some ut with new code

- test/helpers/helpers.go
- test/testgroups/operandbindinfo_group.go
- test/testgroups/operandconfig_group.go
- test/testgroups/operandregistry_group.go
- test/testgroups/operandrequest_group.go
> Enhance operator e2e test

- pkg/controller/operandrequest/operandrequest_controller.go
- pkg/controller/operandrequest/operandrequest_controller_test.go
- pkg/controller/operandrequest/reconcile_operator.go
Fixes #464 
```release-note
```
> Fix operator absent issue

- pkg/apis/operator/v1alpha1/operandconfig_types.go
- pkg/controller/operandbindinfo/operandbindinfo_controller.go
- pkg/controller/operandconfig/operandconfig_controller.go
- pkg/controller/operandregistry/operandregistry_controller.go
- pkg/controller/operandrequest/operandrequest_controller.go
- pkg/controller/operandrequest/reconcile_operand.go
- pkg/controller/operandrequest/reconcile_operator.go
Fixes #466
```release-note
```
> Fix OperandConfig reconcile cannot stop issue

- Makefile
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.4/operand-deployment-lifecycle-manager.v1.2.4.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.4/operator.ibm.com_operandbindinfos_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.4/operator.ibm.com_operandconfigs_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.4/operator.ibm.com_operandregistries_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.4/operator.ibm.com_operandrequests_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/operand-deployment-lifecycle-manager.package.yaml
- version/version.go
> bump 1.2.3 to beta channel and create 1.2.4 for dev channel

- pkg/controller/operandconfig/operandconfig_controller.go
- pkg/controller/operandregistry/operandregistry_controller.go
The finalizer is a good solution to avoid user misuse, remove it at first, later we can discuss if have better solution.
Fixes #
```release-note
```
> Remove finalizer for config and registry

- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.3/operand-deployment-lifecycle-manager.v1.2.3.clusterserviceversion.yaml
This PR is to pick the changes in #469 into the beta channel
Fixes #
```release-note
```
> update odlm image digest in the beta channel

- docs/design/operand-deployment-lifecycle-manager.md
> add install mode to ODLM

- pkg/controller/operandregistry/operandregistry_controller.go
Fixes #475
```release-note
```
> Check catalog source status every 10 mins

- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.3/operand-deployment-lifecycle-manager.v1.2.3.clusterserviceversion.yaml
> Update odlm image digest for csv v1.2.3

- deploy/olm-catalog/operand-deployment-lifecycle-manager/operand-deployment-lifecycle-manager.package.yaml
Bump stable-v1 channel to use the CSV 1.2.3
Fixes #
```release-note
```
> Promote  stable-v1 channel to use CSV 1.2.3

- pkg/controller/operandbindinfo/operandbindinfo_controller.go
- pkg/controller/operandbindinfo/operandbindinfo_controller_test.go
When the OperandBindInfo instance is deleted, the secret and configmap copies owned by this instance will be deleted as well.
Fixes #476 
```release-note
```
> Delete copies when the bindinfo is deleted

- pkg/controller/operandbindinfo/operandbindinfo_controller.go
- pkg/controller/operandrequest/operandrequest_controller.go
- test/helpers/helpers.go
- test/helpers/operandbindinfo.go
- test/helpers/operandconfig.go
- test/helpers/operandregistry.go
- test/helpers/operandrequest.go
- test/helpers/templates.go
- test/testgroups/operandbindinfo_group.go
- test/testgroups/operandconfig_group.go
- test/testgroups/operandregistry_group.go
- test/testgroups/operandrequest_group.go
1. Fix typos in the e2e test
2. Separate `helps.go` into five files for testing ODLM CR and keeping templates
3. Add more test cases into the test group of  OperandRequest, including update the OperandConfig and remove one operator from the OperandRequest.
Fixes #
```release-note
```
> Update e2e test

- Makefile
Fix the image push CICD pipeline.
Fixes #
```release-note
```
> config docker before push the images

- Makefile
Fix the image push CICD pipeline.
Fixes #
```release-note
```
> config docker before pushing images

- Makefile
- controllers/operandbindinfo_controller_test.go
- controllers/suite_test.go
This PR update the unit test cases for the OperandBindinfo controller 
Fixes #
```release-note
```
> Update OperandBindinfo controller unit test

- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manager/manager.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.0/operand-deployment-lifecycle-manager.v1.3.0.clusterserviceversion.yaml
- deploy/operator.yaml
> Remove productVersion metering annotations

- Dockerfile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.0/operand-deployment-lifecycle-manager.v1.3.0.clusterserviceversion.yaml
This PR enabled using ubi as base image for ODLM
Fixes #
```release-note
```
> use ubi as base image for ODLM

- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manager/manager.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.4/operand-deployment-lifecycle-manager.v1.2.4.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.0/operand-deployment-lifecycle-manager.v1.3.0.clusterserviceversion.yaml
This PR is for keeping the operator deployment name unchanged from the previous release.
Fixes #
```release-note
```
> don't change the operator deployment name for odlm

- Makefile
- common/scripts/multiarch_image.sh
> Fix build multi arch image issue

- Dockerfile
- Makefile
This PR removes the hardcoded goarch in the dockerfile
Fixes #
```release-note
```
> Remove the hardcoded goarch

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/default/kustomization.yaml
- config/manager/manager.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/rbac/role.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.0/operand-deployment-lifecycle-manager.v1.3.0.clusterserviceversion.yaml
> Update makefile and bundle manifest template

- Dockerfile
This PR upgrades golang version to 1.14.7 to fix the vulnerability issue.
Fixes #
```release-note
```
> Update go version to 1.14.7

- controllers/operandrequest_controller.go
- controllers/reconcile_operand.go
- controllers/reconcile_operator.go
Fixes #
This PR uses the `klog` to cover the reconciliation failure.
```release-note
```
> catch error logs from the reconciliation failure

- Dockerfile
> add license

- common/scripts/install-kubebuilder.sh
- common/scripts/install-operator-sdk.sh
- controllers/common/fetch.go
- controllers/operandbindinfo_controller.go
- controllers/operandbindinfo_controller_test.go
- controllers/operandconfig_controller.go
- controllers/operandconfig_controller_test.go
- controllers/operandregistry_controller.go
- controllers/operandregistry_controller_test.go
- controllers/operandrequest_controller.go
- controllers/operandrequest_controller_test.go
- controllers/reconcile_operand.go
- controllers/reconcile_operator.go
- controllers/testutil/test_data.go
- controllers/util/merge.go
- controllers/util/merge_test.go
- controllers/util/multi_errors_test.go
- controllers/util/util_suite_test.go
- Add unit test for util files
- Set the error message starting with the lower case to follow this golint `error strings should not be capitalized or end with punctuation or a newline`
- Move test_data from `common` to `testutil`
- Enhance kubbuilder and operator-sdk install script to adapt mac environment.
- Remove unused file `compare_slice.go`
Fixes #
```release-note
```
> Add unit test for util files

- README.md
> Update operator-sdk version

- Makefile
- common/Makefile.common.mk
- controllers/common/fetch.go
- controllers/operandbindinfo_controller_test.go
- controllers/operandconfig_controller_test.go
- controllers/operandregistry_controller_test.go
- controllers/operandrequest_controller_test.go
- controllers/suite_test.go
- controllers/testutil/test_data.go
- go.mod
- go.sum
Add more testing cases with the `envtest` package. 
The code coverage is increased to around `65%`
https://codecov.io/gh/IBM/operand-deployment-lifecycle-manager/tree/159b51495a3425535feff62c1645e38399709ead/controllers
Fixes #490 Fixes #488 Fixes #487  
```release-note
```
> enhance the unit test to increase the code coverage

- controllers/common/fetch.go
- controllers/operandrequest_controller_test.go
- controllers/reconcile_operator.go
- controllers/testutil/test_data.go
- go.mod
> Add a new fetch csv method for delete

- api/v1alpha1/operandregistry_types.go
- api/v1alpha1/operandrequest_types.go
Fix two typos in the code.
Fixes #
```release-note
```
> Fix two typos

- bundle/manifests/operator.ibm.com_operandbindinfos.yaml
- bundle/manifests/operator.ibm.com_operandconfigs.yaml
- bundle/manifests/operator.ibm.com_operandregistries.yaml
- bundle/manifests/operator.ibm.com_operandrequests.yaml
- config/crd/kustomization.yaml
- config/crd/patches/label_in_operandbindinfos.yaml
- config/crd/patches/label_in_operandconfigs.yaml
- config/crd/patches/label_in_operandregistries.yaml
- config/crd/patches/label_in_operandrequests.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.4/operator.ibm.com_operandbindinfos_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.4/operator.ibm.com_operandconfigs_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.4/operator.ibm.com_operandregistries_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.4/operator.ibm.com_operandrequests_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.0/operator.ibm.com_operandbindinfos_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.0/operator.ibm.com_operandconfigs_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.0/operator.ibm.com_operandregistries_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.0/operator.ibm.com_operandrequests_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.1/operator.ibm.com_operandbindinfos_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.1/operator.ibm.com_operandconfigs_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.1/operator.ibm.com_operandregistries_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.1/operator.ibm.com_operandrequests_crd.yaml
Add label to pass the ibm certification
Fixes #
```release-note
```
> Add label for ibm certification

- controllers/operandrequest_controller.go
> Reconcile operand Request every 30 mins

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operand-deployment-lifecycle-manager.v1.4.0.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operator.ibm.com_operandbindinfos_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operator.ibm.com_operandconfigs_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operator.ibm.com_operandregistries_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operator.ibm.com_operandrequests_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/operand-deployment-lifecycle-manager.package.yaml
- version/version.go
bump operator version to 1.4.0
Fixes #
```release-note
```
> bump operator version to 1.4.0

- api/v1alpha1/operandregistry_types.go
- docs/design/operand-deployment-lifecycle-manager.md
Update docs for resolving the confusion of namespace in OperandRegistry.
Fixes #520 
No
```release-note
```
> state the namespace in OperandRegistry

- Makefile
- api/v1alpha1/operandrequest_types.go
- bundle.Dockerfile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- bundle/manifests/operator.ibm.com_operandbindinfos.yaml
- bundle/manifests/operator.ibm.com_operandconfigs.yaml
- bundle/manifests/operator.ibm.com_operandregistries.yaml
- bundle/manifests/operator.ibm.com_operandrequests.yaml
- bundle/metadata/annotations.yaml
- common/Makefile.common.mk
- common/scripts/install-opm.sh
- common/scripts/push-csv.sh
- config/crd/bases/operator.ibm.com_operandregistries.yaml
- config/crd/bases/operator.ibm.com_operandrequests.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operand-deployment-lifecycle-manager.v1.4.0.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operator.ibm.com_operandbindinfos_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operator.ibm.com_operandconfigs_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operator.ibm.com_operandregistries_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operator.ibm.com_operandrequests_crd.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/operand-deployment-lifecycle-manager.package.yaml
- docs/install/install-with-kind.md
- docs/install/install-with-ocp-3.11.md
- docs/install/install.md
Update ODLM package name from `operand-deployment-lifecycle-manager` to `ibm-odlm`.
Fixes #
```release-note
```
> Use ibm-odlm as the package name

- controllers/operandregistry_controller.go
Remove CatalogSource check to avoid cluster permission.
Fixes #531 
```release-note
```
> remove catalogsource check

- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operand-deployment-lifecycle-manager.v1.4.0.clusterserviceversion.yaml
- deploy/operator.yaml
- deploy/role.yaml
- deploy/role_binding.yaml
> fix the permission issue

- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- config/rbac/role.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operand-deployment-lifecycle-manager.v1.4.0.clusterserviceversion.yaml
> update cluster role

- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manager/manager.yaml
- controllers/k8sutil/cache.go
- controllers/operandrequest_controller.go
- controllers/util/util.go
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operand-deployment-lifecycle-manager.v1.4.0.clusterserviceversion.yaml
- go.mod
- main.go
Add watch_namespace to ODLM
Fixes #
```release-note
```
> add watch namespace to ODLM

- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manager/manager.yaml
- controllers/k8sutil/cache.go
- controllers/operandrequest_controller.go
- controllers/util/util.go
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operand-deployment-lifecycle-manager.v1.4.0.clusterserviceversion.yaml
- go.mod
- main.go
If we delete the namespace from the list when the Operandrequest is deleted, when there are multiple operandrequests in the same namespace, it will cause that when one operandrequest is deleted, its namespace will be removed accidentally. 
Update ns scope management
Fixes #
```release-note
```
> Update the logic of namespace scope CR management

- controllers/k8sutil/cache.go
- main.go
Update ODLM cache to add a filter to configmap and secret.
Fixes #
```release-note
```
> update ODLM cache

- controllers/common/fetch.go
- controllers/k8sutil/cache.go
- controllers/operandbindinfo_controller.go
- controllers/operandconfig_controller.go
- controllers/operandregistry_controller.go
- controllers/operandrequest_controller.go
- controllers/reconcile_operator.go
- controllers/util/merge.go
- controllers/util/util.go
- controllers/util/util_test.go
- main.go
1. Update error logs
2. Use gset library
3. ignore status update in the wait loop
Fixes #
```release-note
```
> update error messages and avoid status update error

- controllers/operandbindinfo_controller.go
rename secret configmap when operandrequest is in the same namespace as operandbindinfo
Fixes #
```release-note
```
> rename secret configmap when operandrequest is in the same namespace as operandbindinfo

- controllers/operandrequest_controller.go
> don't remove namespaces from the namespace member list

- controllers/constant/constant.go
update the name of the managed namespace scope CR
Fixes #
```release-note
```
> update the name of the managed namespace scope CR

- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
Remove the replaces from the CSV since the package name is changed.
Fixes #
```release-note
```
> remove replaces

- deploy/olm-catalog/operand-deployment-lifecycle-manager/operand-deployment-lifecycle-manager.package.yaml
> Update csv version in package yaml

- controllers/operandconfig_controller.go
> Check alm-examples empty

- controllers/operandbindinfo_controller.go
- controllers/reconcile_operand.go
> reduce logs from bindinfo

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- version/version.go
bump version to 1.4.1
Fixes #
```release-note
```
> bump version to 1.4.1

- api/v1alpha1/operandrequest_types.go
Condition status records the previous status. It should record the current status.
Fixes #
```release-note
```
> condition status update

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- version/version.go
This PR bumps operator version to 1.5.0
Fixes #
```release-note
```
> bump operator version to 1.5.0

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- version/version.go
bump version to 1.4.2
Fixes #
```release-note
```
> bump version to 1.4.2

- controllers/operandconfig_controller.go
check if the service exists in the operandconfig, then update the status
Fixes #
```release-note
```
> check if the service exists in the opcon, then update the status

- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manager/manager.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.1/operand-deployment-lifecycle-manager.v1.2.1.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.2/operand-deployment-lifecycle-manager.v1.2.2.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.3/operand-deployment-lifecycle-manager.v1.2.3.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.4/operand-deployment-lifecycle-manager.v1.2.4.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.0/operand-deployment-lifecycle-manager.v1.3.0.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.1/operand-deployment-lifecycle-manager.v1.3.1.clusterserviceversion.yaml
- deploy/operator.yaml
Update labels
```
beta.kubernetes.io/arch -> kubernetes.io/arch
beta.kubernetes.io/os -> kubernetes.io/os
```
Fixes #
```release-note
```
> Use label kubernetes.io

- controllers/operandrequest_controller.go
- go.mod
> Move add namespace member to the front of update

- controllers/operandrequest_controller.go
- go.mod
Fixes #
Follow up #566 
```release-note
```
> tidy go.mod

- api/v1alpha1/operandconfig_types.go
- api/v1alpha1/operandregistry_types.go
- controllers/operandbindinfo/operandbindinfo_controller.go
- controllers/operandconfig/operandconfig_controller.go
- controllers/operandregistry/operandregistry_controller.go
- controllers/operandrequest/operandrequest_controller.go
Only update CR status once in the reconciliation.
Fixes #
```release-note
```
> Only update status once in the reconciliation

- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/rbac/role.yaml
fix issue #584 
Please hold a second for merging, in the process of testing whether need more permission
> grant permission for ODLM CRDs

- Makefile
- controllers/deploy/manager.go
- controllers/operandbindinfo/operandbindinfo_controller.go
- controllers/operandbindinfo/operandbindinfo_suite_test.go
- controllers/operandconfig/operandconfig_controller.go
- controllers/operandconfig/operandconfig_suite_test.go
- controllers/operandregistry/operandregistry_controller.go
- controllers/operandregistry/operandregistry_suite_test.go
- controllers/operandrequest/operandrequest_controller.go
- controllers/operandrequest/operandrequest_controller_suit_test.go
- controllers/operandrequest/reconcile_operand.go
- controllers/operandrequest/reconcile_operator.go
- main.go
This PR picks the change from this PR: https://github.com/IBM/operand-deployment-lifecycle-manager/pull/517
Close: https://github.com/IBM/operand-deployment-lifecycle-manager/pull/517
Fixes #
```release-note
```
> Move fetch method to manager.go

- controllers/deploy/manager.go
- controllers/operandbindinfo/operandbindinfo_controller.go
- controllers/operandconfig/operandconfig_controller.go
- controllers/operandrequest/operandrequest_controller.go
- controllers/operandrequest/reconcile_operand.go
- controllers/operandrequest/reconcile_operator.go
Avoid using API reader to cause extra api calls.
Fixes #
```release-note
```
> Avoid to use api reader to cause extra api call.

- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manager/manager.yaml
Using log level 1 in the runtime, using level 2 for debugging.
Fixes #564
```release-note
```
> Using level 1 in the runtime, using level 2 for debugging

- api/v1alpha1/operandregistry_types.go
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- controllers/operandrequest/reconcile_operator.go
We need to support users in updating packages catalogs and approvals of the subscription.
Fixes #471
```release-note
```
>  Support package catalog and approvall updating in the subscription

- go.mod
- go.sum
fix vulnerability issue CVE-2021-3121
https://github.com/gogo/protobuf/commit/b03c65ea87cdc3521ede29f62fe3ce239267c1bc
Fixes #
```release-note
```
> fix vulnerability issue CVE-2021-3121

- Makefile
- common/Makefile.common.mk
- controllers/constant/constant.go
- controllers/k8sutil/cache.go
- controllers/operandbindinfo/operandbindinfo_controller.go
- controllers/operandbindinfo/operandbindinfo_suite_test.go
- controllers/operandconfig/operandconfig_controller.go
- controllers/operandconfig/operandconfig_suite_test.go
- controllers/operandregistry/operandregistry_controller.go
- controllers/operandregistry/operandregistry_suite_test.go
- controllers/operandrequest/operandrequest_controller.go
- controllers/operandrequest/operandrequest_suit_test.go
- controllers/operandrequest/reconcile_operand.go
- controllers/operandrequest/reconcile_operator.go
- controllers/operator/manager.go
- controllers/util/multi_errors.go
- controllers/util/multi_errors_test.go
- go.mod
- main.go
1. abstract odlm operators 
2. rename Fetch prefix function to get and list
3. Use defer to handle the status update
4. Pass context chain into request functions
5. Set default value to subscription install approval mode
6. One error is only reported once
7. upate multierr template
Refers #587 
```release-note
```
> Refactor some functions

- go.mod
- go.sum
Fix gogo/protobuf vulnerability https://github.com/IBM/operand-deployment-lifecycle-manager/pull/594
Fixes #
```release-note
```
> Porting protobuf fix to EUS

- common/Makefile.common.mk
Update jenkins API source to pass ut.
Fixes #
```release-note
```
> update jeknis source

- controllers/operandrequest/reconcile_operator.go
fix namespace check logic
Fixes #
```release-note
```
> fix: fix namespace check logic

- OWNERS
> added bitscuit and Daniel-Fan to OWNERS

- controllers/operandregistry/operandregistry_controller.go
- controllers/operandrequest/operandrequest_controller.go
- controllers/operandrequest/reconcile_operator.go
- controllers/operator/manager.go
1. Add labels by patch
2. Add a function to collect all the OperandRequest using a sepcific OperandRegistry
Fixes #
```release-note
```
> feat: operandregistry status update

- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
- deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.1/operand-deployment-lifecycle-manager.v1.2.1.clusterserviceversion.yaml
- docs/user/how-to-update-operandregistry.md
- docs/user/how-to-use-operandBindInfo.md
> replace deprecated api

- controllers/constant/constant.go
- controllers/operandrequest/reconcile_operator.go
> feat: add annotation to indicate if the operandregistry is found

- controllers/operandconfig/operandconfig_controller.go
- controllers/operandrequest/operandrequest_controller.go
- controllers/operandrequest/reconcile_operand.go
- controllers/operandrequest/reconcile_operator.go
> adjust log level

- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/rbac/role.yaml
> fix: Avoid having the permission to use any scc

- controllers/operandbindinfo_controller.go
> handle that not found operator in operandregistry in release-1.4

- CONTRIBUTING.md
- Makefile
- OWNERS
- SECURITY_CONTACTS
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- version/version.go
bump operator version to 1.6.0
Fixes #
```release-note
```
> bump operator version to 1.6.0

- docs/design/comparison-to-olm.md
Fixes #628 
```release-note
```
> docs: Add a document to compare OLM and ODLM

- Dockerfile
> updated golang and ubi images to 1.15.10 and 8.3-291, respectively

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- version/version.go
> bump version to 1.4.3

- Dockerfile
> updated ubi8 image to 8.3-298

- controllers/operandbindinfo/operandbindinfo_controller.go
- controllers/operandconfig/operandconfig_controller.go
- controllers/operandregistry/operandregistry_controller.go
- controllers/operandrequest/operandrequest_controller.go
- controllers/operandrequest/operandrequest_controller_test.go
- controllers/operandrequest/reconcile_operand.go
- controllers/operandrequest/reconcile_operator.go
fix #637
Fixes #
```release-note
```
> feat: Apply the ALM example increment to existing CRs 

- controllers/operator/manager.go
Fixes #652 
```release-note
```
> feat: ODLM can check the existing subscription by packagenames

- api/v1alpha1/operandconfig_types.go
- bundle/manifests/operator.ibm.com_operandconfigs.yaml
- config/crd/bases/operator.ibm.com_operandconfigs.yaml
- controllers/operandrequest/operandrequest_controller_test.go
> fix: preserve unknown fields in OperandConfig

- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manager/manager.yaml
> add imagepullpolicy

- controllers/operandrequest/reconcile_operand.go
Fixes #382 
```release-note
```
> feat(Add warning message when can't find customresource in CSV):

- Makefile
> fix codecov

- controllers/namespacescope/namespacescope_controller.go
> fix: continue the loop when namespacescope cr is not found

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- version/version.go
> bump version to 1.5.1

- controllers/operandrequest/reconcile_operand.go
It is the cherry-pick of https://github.com/IBM/operand-deployment-lifecycle-manager/pull/659
Let's hold it until the release of 3.7.3
> add complete err check

- api/v1alpha1/operandconfig_types.go
- api/v1alpha1/operandregistry_types.go
- bundle/manifests/operator.ibm.com_operandregistries.yaml
- config/crd/bases/operator.ibm.com_operandregistries.yaml
- controllers/operandrequest/reconcile_operator.go
> Add startingCSV into the OperandRegistry

- controllers/util/util.go
- main.go
> change env var from ODLM_SCOPE to ISOLATED_MODE

- controllers/operandrequest/reconcile_operator.go
Test error on prow
http://prow.purple-chesterfield.com/log?job=test-operand-deployment-lifecycle-manager-amd64&id=1391867728523956225
http://prow.purple-chesterfield.com/log?job=kind-e2e-test-operand-deployment-lifecycle-manager-amd64&id=1391867728523956226
> Update OperandConfig Annotation

- Makefile
- api/v1alpha1/operandrequest_types.go
- config/e2e/crd/bases/operator.ibm.com_namespacescopes.yaml
- config/e2e/crd/bases/operator.ibm.com_operandbindinfos.yaml
- config/e2e/crd/bases/operator.ibm.com_operandconfigs.yaml
- config/e2e/crd/bases/operator.ibm.com_operandregistries.yaml
- config/e2e/crd/bases/operator.ibm.com_operandrequests.yaml
- config/e2e/crd/kustomization.yaml
- config/e2e/kustomization.yaml
- controllers/namespacescope/namespacescope_controller.go
- controllers/operandrequest/operandrequest_controller.go
- controllers/operandrequest/operandrequest_controller_test.go
- controllers/operandrequest/operandrequest_suite_test.go
- controllers/operandrequest/reconcile_operand.go
- controllers/operandrequest/reconcile_operator.go
- controllers/operator/manager.go
- main.go
user can use the flag "-batch-chunk-size" to control how many subscriptions will be deployed simultaneously
Fixes #624 
```release-note
```
> feat: Install operators in batch.

- controllers/operandconfig/operandconfig_controller.go
- controllers/operandrequest/reconcile_operand.go
> fix: add more checkings in alm-example for unexpected panic

- controllers/operandrequest/reconcile_operand.go
> remove debug logs

- docs/user/how-to-use-operandBindInfo.md
> Updated the OperandBindInfo sample

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- version/version.go
> bump operator version to 1.6.1

- PROJECT
- bundle.Dockerfile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- bundle/manifests/operator.ibm.com_operandbindinfos.yaml
- bundle/manifests/operator.ibm.com_operandconfigs.yaml
- bundle/manifests/operator.ibm.com_operandregistries.yaml
- bundle/manifests/operator.ibm.com_operandrequests.yaml
- bundle/metadata/annotations.yaml
- config/crd/bases/operator.ibm.com_operandbindinfos.yaml
- config/crd/bases/operator.ibm.com_operandconfigs.yaml
- config/crd/bases/operator.ibm.com_operandregistries.yaml
- config/crd/bases/operator.ibm.com_operandrequests.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
> add minKubeVersion and update operator-sdk (#696)

- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- bundle/manifests/operator.ibm.com_operandconfigs.yaml
- config/crd/bases/operator.ibm.com_operandconfigs.yaml
> add preserve-unknown-fields and correct WATCHNAMESPACE

- bundle.Dockerfile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- bundle/manifests/operand-deployment-lifecycle-manager_v1_serviceaccount.yaml
- bundle/metadata/annotations.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
> fix: Remove service account from operator bundle manifest

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- common/Makefile.common.mk
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- go.mod
- go.sum
> Update readme in CSV

- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manager/manager.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- main.go
> Add health and ready probe

- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manager/manager.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
> chore: Add licenses used in the operator

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- version/version.go
> bump version to 1.7.1

- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manager/manager.yaml
> perf: shorten initial delay of readness probe

- controllers/operator/manager.go
> Get csv even the installPlan requires Approval (#723)

- Makefile
> using v0.6.2 version envtest

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- version/version.go
> bump version to 1.10.0

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- version/version.go
> bump version to 1.12.0

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- version/version.go
> bump version to 1.13

- controllers/operandrequest/reconcile_operand.go
- controllers/operator/manager.go
> refactor: refactor CSV fetcher and operator status checker

- controllers/operandconfig/operandconfig_controller.go
> fix: Set creating status if the target CR is not found

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- version/version.go
> chore: Bump operator version to 1.14.0

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- version/version.go
> chore: bump operator to 1.4.5

- controllers/operandbindinfo/operandbindinfo_controller.go
> fix: reconciling bindinfo controller when the original secret is deleted

- controllers/util/util.go
- main.go
> add OPERATORCHECKER_MODE flag for OperatorChecker

- controllers/operatorchecker/operatorchecker_controller.go
> get csv by packageName in OperatorChecker

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- version/version.go
> chore: Update operator version to 1.15.0

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- version/version.go
> bump ODLM efix versions for cs v3.16.2 fix

- controllers/operatorchecker/operatorchecker_controller.go
> fix: remove the operator checker for the operator upgrade

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- version/version.go
> bump version to 1.16.0

- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- common/Makefile.common.mk
- config/manager/manager.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- controllers/operandbindinfo/operandbindinfo_controller.go
- controllers/operandconfig/operandconfig_controller.go
> migrate to ICR registry

- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
> add replaces back to CSV

- Makefile
- OWNERS
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- version/version.go
Bump ODLM version to 1.17.0
Fixes #
```release-note
```
> bump odlm to 1.17.0

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- docs/install/install-with-kind.md
- docs/install/install.md
> update channel from v3 to v3.20

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- version/version.go
Signed-off-by: Ben Luzarraga <luzarragaben@ibm.com>
> bump version to 1.19.0

- controllers/operator/manager.go
ODLM will ignore the CatalogSource excluded in OperandRegistry annotation
```
excluded-catalogsource: catalogsource1, catalogsource2
```
Pre-requisite: Install CS from CatalogSource `opencloud-operator`
1. add annotation into `common-service` OperandRegistry
```
excluded-catalogsource: certified-operators,community-operators,redhat-marketplace,redhat-operators
```
2. Deploy OperandRequest
```
metadata:
labels:
app.kubernetes.io/instance: operand-deployment-lifecycle-manager
app.kubernetes.io/managed-by: operand-deployment-lifecycle-manager
app.kubernetes.io/name: operand-deployment-lifecycle-manager
name: example-service
namespace: cs-2
spec:
requests:
- operands:
- name: …
```
> add excluded CatalogSource annotation for Registry

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- version/version.go
Signed-off-by: YCShen1010 <yuchen.shen@mail.utoronto.ca>
Fixes #
```release-note
```
> odlm version bump to 3.19.5

- controllers/operator/manager.go
- controllers/util/util.go
Replace for automatic cherry-pick #832  in order to add `Contains` function
> [release-ltsr] add excluded CatalogSource annotation for Registry

- common/scripts/next-csv.sh
Made a new PR for cherry-picking version bump script update commits
> [LTSR] Update version bump script

- controllers/operandrequest/reconcile_operand.go
Signed-off-by: YCShen1010 
Related issue: [54892](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/54892)
> Removed partial installplan condition checks and added csv check in operand reconciliation

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- version/version.go
> odlm version bump to 1.20.0

- controllers/operandrequest/reconcile_operand.go
Remove installplan condition check (#841)
* using csv check instead of installplan status check
Signed-off-by: YCShen1010 
* use wanring msg for installplan installing status
Signed-off-by: YCShen1010 
* combined commit for format fix
Signed-off-by: YCShen1010 
Signed-off-by: YCShen1010
> [ODLM] cherry-pick installplan check

- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manager/manager.yaml
> Relax Readiness probe in ODLM pod by increasing the initial delay time

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- version/version.go
Signed-off-by: qpdpQ <liyuchen223@gmail.com>
> bump ltsr to 1.17.5

- controllers/operandrequest/reconcile_operand.go
> remove csv phase check in ODLM

- Makefile
> remove quay image build support

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- version/version.go
> bump to version 3.23.0

- api/v1alpha1/operandrequest_types.go
- controllers/operandrequest/operandrequest_controller.go
- controllers/operandrequest/reconcile_operand.go
- controllers/operandrequest/reconcile_operator.go
reserve the status for operators which are still in deletion stage
> reserve the status for operators which are still in deletion stage (#867)

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- version/version.go
Signed-off-by: Ben Luzarraga <luzarragaben@ibm.com>
> bump version for 3.19.8

- controllers/operandbindinfo/operandbindinfo_controller.go
> refresh pod only when secret and configmap updated

- Dockerfile
- Makefile
- common/scripts/artifactory_config_docker.sh
> new artifactory image endpoint (odlm)

- Dockerfile
- Makefile
- common/scripts/artifactory_config_docker.sh
> [ltsr] new artifactory image endpoint (odlm)

- api/v1alpha1/operandconfig_types.go
- api/v1alpha1/operandrequest_types.go
- bundle/manifests/operator.ibm.com_operandrequests.yaml
- controllers/k8sutil/cache.go
- controllers/operandrequest/reconcile_operand.go
- controllers/util/util.go
- go.mod
- go.sum
- test/e2e/helpers_test.go
update how odlm reports status in a given operand request
> ODLM updated status projection

- Dockerfile
- api/v1alpha1/operandconfig_types.go
- api/v1alpha1/operandrequest_types.go
- controllers/k8sutil/cache.go
- controllers/util/util.go
- go.mod
- go.sum
- test/e2e/helpers_test.go
> update go mod to 1.20

- bundle/manifests/operator.ibm.com_operandrequests.yaml
add preserve unknown fields to status section for OperandRequest Status reporting
> add preserve unknown fields to operandrequest status

- api/v1alpha1/operandrequest_types.go
- controllers/operandrequest/reconcile_operand.go
- controllers/operandrequest/reconcile_operator.go
- controllers/operator/manager.go
> Indicate multi requested service version conflict

- controllers/operandconfig/operandconfig_controller.go
- controllers/operandrequest/reconcile_operand.go
- controllers/operandrequest/reconcile_operator.go
- controllers/operator/manager.go
Issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/58225
Pending for description..............
> manage complete tenant scope for subscriptions

- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
for issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/58764
> [ODLM LTSR] "disconnected" annotation for certification assessment

- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manager/manager.yaml
fix for: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58680#issuecomment-58290268
> [LTSR] Update ImagePullPolicy to IfNotPresent

- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manager/manager.yaml
fix for: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58680#issuecomment-58290268
> [BD 4.1] Update ImagePullPolicy to IfNotPresent

- controllers/operandbindinfo/operandbindinfo_controller.go
for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59166
allow multiple operandBindInfo in different namespaces mounting the same secret.
> multiple opbi

- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manager/manager.yaml
for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59738
> add ephemeral-storage request to container

- controllers/operandrequest/reconcile_operand.go
> [LTSR] set OwnerReference for resources created by OperandRequest

- controllers/operandbindinfo/operandbindinfo_controller.go
- controllers/operandrequest/reconcile_operand.go
addressed issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/61126
cherry pick https://github.com/IBM/operand-deployment-lifecycle-manager/pull/999/files
> [LTSR] allow to add multiple owner references to cm/secret

- controllers/operandrequest/reconcile_operand.go
To address issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61292#issuecomment-67479970
ODLM should not reconcile any CRs whose operator has been marked as `no-op` in OperandRegistry
For example, `ibm-management-ingress-operator` is marked as `no-op` in OperandRegistry.
```
- sourceNamespace: openshift-marketplace
channel: v3.23
name: ibm-management-ingress-operator
packageName: ibm-management-ingress-operator-app
installMode: no-op
```
Any changes to `mgmt-ingress` CR in OperandConfig should not be fetched, and applied to the CR in the cluster by ODLM
```
- name: ibm-management-ingress-operator
spec:
managementIngress:
multipleInstancesEnabled: false -------> true     // This change should not be applied to CR in the cluster
replicas: 1
resources:
limits:
cpu: 1000m
memory: …
```
> Skip reconciling CRs for operators marked as no-op

- Makefile
- api/v1alpha1/operandconfig_types.go
- api/v1alpha1/operandregistry_types.go
- bundle.Dockerfile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- bundle/manifests/operator.ibm.com_operandbindinfos.yaml
- bundle/manifests/operator.ibm.com_operandconfigs.yaml
- bundle/manifests/operator.ibm.com_operandregistries.yaml
- bundle/manifests/operator.ibm.com_operandrequests.yaml
- bundle/metadata/annotations.yaml
- bundle/tests/scorecard/config.yaml
- config/crd/bases/operator.ibm.com_operandbindinfos.yaml
- config/crd/bases/operator.ibm.com_operandconfigs.yaml
- config/crd/bases/operator.ibm.com_operandregistries.yaml
- config/crd/bases/operator.ibm.com_operandrequests.yaml
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62607
> Update CRD to add preserve unknown fields

- api/v1alpha1/operandconfig_types.go
Fix for: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65006
> Omit empty value in CRD

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- version/version.go
> Bump version to 4.3.8 for CS 4.6.9

- OWNERS
> Update OWNERS with my Id

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- version/version.go
**What this PR does / why we need it**: Bump version to 4.3.10 for CS 4.6.11
Fixes # N/A
```release-note
```
> Bump version to 4.3.10 for CS 4.6.11

- controllers/operator/manager.go
- helm-cluster-scoped/templates/crd.yaml
- helm-cluster-scoped/values.yaml
- helm/templates/operator-deployment.yaml
- helm/templates/rbac.yaml
- helm/values.yaml
Rebase master branch onto release-future
> Rebase master branch onto future

- helm-cluster-scoped/templates/cluster-rbac.yaml
- helm-cluster-scoped/templates/cluster-webhook.yaml
- helm/templates/operator-deployment.yaml
- helm/templates/rbac.yaml
- helm/values.yaml
removed dependency on namespace-scope configmap
added generic configuration of labels
added cpfs scoped imagePullPrefix for dev testing
> fixes and enhancements to chart

- api/v1alpha1/operandrequest_types.go
- controllers/operandrequest/operandrequest_controller.go
- controllers/operandrequest/reconcile_operand.go
> [SC2] Refactor service status update logic to remove unnecessary context and client parameters

- controllers/operandrequest/operandrequest_controller.go
> [SC2] Add debug logging for reconciliation events

- controllers/operandbindinfo/operandbindinfo_controller.go
> [SC2] Refactor Bindinfo controller logic on object event watching and reconciliation triggering condition

- controllers/operandbindinfo/operandbindinfo_controller.go
cherry-pick of https://github.com/IBM/operand-deployment-lifecycle-manager/pull/1157
> use reader.Get to get resource in cluster

- common/scripts/lint_go.sh
- controllers/operator/manager.go
> [SC2] Refactor fallback channel selection to sort by semantic version and find the first available channel

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- helm-cluster-scoped/Chart.yaml
- helm/Chart.yaml
- helm/templates/operator-deployment.yaml
- version/version.go
> Bump ODLM version up to 4.5.2

- Makefile
- bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
- helm-cluster-scoped/Chart.yaml
- helm/Chart.yaml
- helm/templates/operator-deployment.yaml
- version/version.go
> Bump ODLM version to 4.5.3
