IBM/operand-deployment-lifecycle-manager

common/Makefile.common.mk

This will solve the openapi-gen relative and absolute path issue.
/cc @DanielXLee @horis233

workaround to solve the code-gen path issue

---

Makefile
build/Dockerfile.ppc64le
build/Dockerfile.s390x

fixes https://github.com/IBM/meta-operator/issues/39
The newly added targets will be skipped when running on non-amd64 machine.
/cc @morvencao @gyliu513 @DanielXLee @horis233

build multiarch images on amd64 machine

---

pkg/apis/operator/v1alpha1/metaoperatorcatalog_types.go
pkg/apis/operator/v1alpha1/metaoperatorconfig_types.go
pkg/controller/metaoperatorset/catalog_status.go
pkg/controller/metaoperatorset/config_status.go
pkg/controller/metaoperatorset/metaoperatorset_controller.go

#47 #45 
operator-sdk scorecard tests the `status` field of the CR when they are created.

Add init status for config and catalog

---

docs/dev/e2e.md
docs/install/common-service-integration.md
docs/install/install-with-kind.md
docs/install/install.md

This PR is used to update the namespace in the document to the `ibm-common-services`.
```
None
```
```release-note
NONE
```

Update namespace to ibm-common-services

---

deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml

based on Mike's comment, the OperandRegistry & OperandConfigs CRs should be deployed in the `ibm-common-services` namespace. 
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/34718#issuecomment-18154542
Fixes #
```release-note
NONE
```

add default namespace for OperandRegistry & OperandConfigs seed CRs 

---

deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml

This PR integrates IBM Monitoring Prometheus Operator Extension for easier to use and enhanced Prometheus deployment.
```release-note
NONE
```

integrate IBM Monitoring Prometheus Operator Extension

---

deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml

Common services need a shared CA, and this uses the `operandConfig` so that the ODLM can have the shared CA's cert-manager CRs get created when deploying the cert-manager-operator's CR.
Fixes #
```release-note
NONE 
```

Add the cert-manager crs used to create the shared ca.

---

Makefile
pkg/apis/operator/v1alpha1/operandrequest_types.go
pkg/controller/operandrequest/operandrequest_controller.go

The registryNamespace is an optional property inside of OperandRequest, if user don't set this value when creating an OperandRequest CR, OperandRequest controller will set a default value is the current namespace in which the request is defined
Fixes #191
```release-note
```

Add default handle logic for registryNamespace

---

deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml

This PR adds the navconfiguration CRs to commonui-operator for providing default navItems.
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/36315

adding navconfig to common-ui

---

deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
pkg/controller/operandrequest/config_status.go
pkg/controller/operandrequest/operandrequest_controller.go
pkg/controller/operandrequest/reconcile_operand.go
pkg/util/lcFirst.go

Fixes #199 
This PR is used to implement the function when the CR is removed from the operandconfig ODLM can remove the CR from the cluster.
Moreover, expose more error messages in the logs.
```release-note
NONE
```

Operandconfig delete

---

deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
pkg/apis/operator/v1alpha1/operandconfig_types.go

This PR is for passing the RH certification.
RH certification will deploy the operator in their testing environment and do some tests, but their environment doesn't have `ibm-common-services` namespace. 
So, I make this PR to clear up the hard code namespace in the ODLM 
```release-note
```

remove ibm-common-services namespace

---

deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml
pkg/controller/operandrequest/config_status.go
pkg/controller/operandrequest/reconcile_operand.go
pkg/controller/operandrequest/reconcile_operator.go
pkg/controller/operandrequest/request_status.go

**Which issue(s) this PR fixes**
Fixes #203  
Fixes #202 
This PR is used to refactoring Operand Config reconcile.
- Modularized reconcile to CRUD
- Adjust logging level in Operand Config reconcile.
- When there is no custom resource is required,  the cluster phase will be `running`, even is the operand phase is `ready`.
```release-note
NONE
```

Refactor operandConfig reconcile

---

pkg/controller/operandconfig/operandconfig_controller_test.go
pkg/controller/operandregistry/operandregistry_controller.go
pkg/controller/operandregistry/operandregistry_controller_test.go
pkg/controller/operandrequest/operandrequest_controller_test.go

```console
go: github.com/jstemmer/go-junit-report upgrade => v0.9.1
Code coverage test (concurrency 6)
?   	github.com/IBM/operand-deployment-lifecycle-manager/pkg/apis/operator	[no test files]
?   	github.com/IBM/operand-deployment-lifecycle-manager/pkg/apis	[no test files]
?   	github.com/IBM/operand-deployment-lifecycle-manager/pkg/apis/operator/v1alpha1	[no test files]
?   	github.com/IBM/operand-deployment-lifecycle-manager/pkg/controller	[no test files]
?   	github.com/IBM/operand-deployment-lifecycle-manager/cmd/manager	[no test files]
?   	github.com/IBM/operand-deployment-lifecycle-manager/test/config	[no test files]
?   	github.com/IBM/operand-deployment-lifecycle-manager/pkg/util	[no test files]
? …
```

Update the unit test to increase coverage

---

Makefile
pkg/controller/operandrequest/config_status.go
pkg/controller/operandrequest/operandrequest_controller_test.go
pkg/controller/operandrequest/request_status.go

1. add present operator for unit test
2. only run unit test for controller
3. fix some status issue
```console
go: github.com/jstemmer/go-junit-report upgrade => v0.9.1
Code coverage test (concurrency 6)
?   	github.com/IBM/operand-deployment-lifecycle-manager/pkg/controller	[no test files]
ok  	github.com/IBM/operand-deployment-lifecycle-manager/pkg/controller/operandconfig	1.180s	coverage: 28.0% of statements
ok  	github.com/IBM/operand-deployment-lifecycle-manager/pkg/controller/operandregistry	1.670s	coverage: 37.5% of statements
ok  	github.com/IBM/operand-deployment-lifecycle-manager/pkg/controller/operandrequest	2.078s	coverage: 64.6% of statements
```
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes …

Support present operator for the  operand request unit test

---

pkg/apis/operator/v1alpha1/operandrequest_types.go

Ref #47 
Scorecard check needs a status field in the operandRequest instance when initializing.
```release-note
NONE
```

set default phase to operandRequest

---

pkg/apis/operator/v1alpha1/operandrequest_types.go
pkg/controller/operandrequest/operandrequest_controller.go
pkg/controller/operandrequest/operandrequest_controller_test.go
pkg/controller/operandrequest/reconcile_operator.go
pkg/controller/operandrequest/request_status.go

1. Move Cluster Phase update code logic to OperandRequest API
2. Remove getOperatorPhase func, to use the phase from OperandRegistry instance status.
3. Update OperandRequest UT
Fixes #
```release-note
```

Update operandrequest member status with new phase

---

pkg/apis/operator/v1alpha1/operandconfig_types.go
pkg/apis/operator/v1alpha1/operandregistry_types.go
pkg/controller/operandregistry/operandregistry_controller_test.go
pkg/controller/operandrequest/config_status.go
pkg/controller/operandrequest/registry_status.go

Scorecard needs every init status has a descriptor,  but the `serviceStatus` in the `operandConfig` and `operatorStatus` in the `operandRegistry` can't find suitable descriptor structure.  
So I update the ODLM to only init the phase in the `operandConfig` and `operatorStatus` instance and move `serviceStatus` and `operatorStatus` initialization to the `OperandRequest` reconcile.
Ref #44 
```release-note
NONE
```

Update status init for passing the rh certification

---

README.md
common/scripts/codecov.sh
pkg/apis/operator/v1alpha1/operandconfig_types.go
pkg/apis/operator/v1alpha1/operandregistry_types.go
pkg/controller/operandconfig/operandconfig_controller_test.go
pkg/controller/operandregistry/operandregistry_controller_test.go
pkg/controller/operandrequest/config_status.go
pkg/controller/operandrequest/operandrequest_controller_test.go
pkg/controller/operandrequest/request_status.go

- Set ready as the init status for OperandConfig and OperandRegistry instance.
- Add custom resource deleting into the unit test.
- Add code coverage into the readme.
- Clean up status when the custom resource is deleted from the OperandConfig.
```release-note
NONE
```

Enhance unit test

---

pkg/controller/operandrequest/operandrequest_controller.go
pkg/controller/operandrequest/operandrequest_controller_test.go
pkg/controller/operandrequest/reconcile_operator.go
pkg/controller/operandrequest/request_status.go

Enhance OperandRequest member status update:
- Waiting for Subscription is ready then update OperandRequest member status instead update the member status just after subscriptions are created.
```release-note
NONE
```

Move member status update after waiting for subscriptions ready

---

Makefile

update retry times and interval for multiarch image build,
to fix multi-arch build timeout failure: http://prow.purple-chesterfield.com/log?job=multiarch-image-operand-deployment-lifecycle-manager-postsubmit&id=1241909811491115008
Fixes #
```release-note
```

update retry times and interval for multiarch image build.

---

deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml

Fixes #
This is to onboard prometheus-operator to remove crd dependency. 
This is to onboard prometheus-operator to remove crd dependency. 
```release-note
None
```

onboard prometheus operator as crd dependency is deprecated by ODLM

---

pkg/controller/operandrequest/reconcile_operand.go

Delete custom resource panic error if the service does not exist in the config.
```console
E0324 10:30:03.078276   69117 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 957 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x2016a60, 0x2e67600)
/Users/danielxlee/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/Users/danielxlee/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/runtime/runtime.go:48 +0x82
panic(0x2016a60, 0x2e67600)
/usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:967 …
```

Fix delete operand request issue

---

Makefile
common/scripts/multiarch_image.sh

Fix image version from `v${date}-${hash}` to `${hash}` since CICD process just will only recognize the latter one.
Fixes #
```release-note
```

fix image version.

---

deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml
deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
deploy/olm-catalog/operand-deployment-lifecycle-manager/0.0.1/operand-deployment-lifecycle-manager.v0.0.1.clusterserviceversion.yaml

This PR removes prometheus-operator from CRs and CSV. Prometheus operator is installed by prometheus-ext operator directly now
Fixes #
```release-note
None
```

Remove prometheus-operator from CRs and CSV

---

pkg/controller/operandrequest/reconcile_operator.go

When creating an operand request, if the registry or registrynamespace not correct, there is no error message or event for it.
Fixes #
```release-note
```

Add event when operandregistry not found

---

deploy/crds/operator.ibm.com_v1alpha1_operandrequest_cr.yaml
deploy/olm-catalog/operand-deployment-lifecycle-manager/1.1.0/operand-deployment-lifecycle-manager.v1.1.0.clusterserviceversion.yaml
pkg/apis/operator/v1alpha1/operandconfig_types.go
pkg/apis/operator/v1alpha1/operandregistry_types.go
pkg/apis/operator/v1alpha1/operandrequest_types.go

1. Enable all the services
2. Add resources annotation for each crd
```release-note
NONE
```

Add resource annotation and enable all common services

---

pkg/apis/operator/v1alpha1/operandconfig_types.go
pkg/apis/operator/v1alpha1/operandregistry_types.go
pkg/controller/operandrequest/operandrequest_controller.go
pkg/controller/operandrequest/reconcile_operand.go
pkg/controller/operandrequest/reconcile_operator.go

1. Move getOperatorFromRegistryInstance method to OperandRegistry api
2. Move getServiceFromConfigInstance method to OperandConfig api
Fixes #303 
```release-note
```

Move some methods to api

---

pkg/controller/operandbindinfo/operandbindinfo_controller.go

Reconcile method too long, split copyconfigmap and copysecret as separate methods
Fixes #
```release-note
```

Restruct the bindinfo controller

---

pkg/controller/operandrequest/reconcile_operand.go

ODLM will skip operand custom resource update when custom resource specs are deeply equal.
```release-note
NONE
```

Skip operand update when specs are same

---

deploy/crds/operator.ibm.com_operandbindinfos_crd.yaml
deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operator.ibm.com_operandbindinfos_crd.yaml
pkg/apis/operator/v1alpha1/operandbindinfo_types.go
pkg/apis/operator/v1alpha1/operandrequest_types.go
pkg/controller/operandbindinfo/operandbindinfo_controller.go
pkg/controller/operandregistry/operandregistry_controller.go

- Add optional `registryNamespace` into the OperandBindinfo CRD.
- Add `OperandRegistry` label to the OperandBindInfo for #317 #322  
Fixes #317 Fixes #323 
```release-note
NONE
```

Add label into Operandbindinfo instance

---

pkg/controller/operandbindinfo/operandbindinfo_controller_test.go
pkg/controller/operandconfig/operandconfig_controller_test.go
pkg/controller/operandregistry/operandregistry_controller_test.go
pkg/controller/operandrequest/operandrequest_controller_test.go

This PR is for enhancing the unit test for 2Q feature
- Deploy `OperandRequest` and `OperandRegistry`, `OperandConfig` into different namespace.
- Use different name for `OperandRequest` and `OperandRegistry`, `OperandConfig`.
- Test the case: `OperandRegistry`, `OperandConfig` instance are updated.
- Update comments 
Fixes #333 
```release-note
NONE
```

Enhance unit test for 2Q

---

deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml
deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
pkg/controller/operandbindinfo/operandbindinfo_controller.go
pkg/controller/operandconfig/operandconfig_controller.go
pkg/controller/operandrequest/reconcile_operand.go
pkg/controller/operandrequest/reconcile_operator.go

- Remove `navconfiguration: {}` from OperandConfig
- When updating configmap and/or secret, compare the content of configmap and/or secret. If there is no change, then skip the update.
- When updating operand CR, only show `Updating` logs when the operand CR `spec` is updated.
- The OperandConfig controller will ignore the OperandConfig status changes.
- Add logs to clarify `Operator` and `Operand` reconcile finished.
Fixes #338  …

Enhance operandConfig reconcile

---

pkg/apis/operator/v1alpha1/operandbindinfo_types.go

BindInfo init status cannot be initialized
Fixes #
```release-note
```

Fix OperandBindInfo init stauts issue

---

pkg/controller/operandbindinfo/operandbindinfo_controller.go
pkg/controller/operandbindinfo/operandbindinfo_controller_test.go

If the `requestNamespaces` less than 2, means there is one request or not.
If not, we certainly do not have to
If there is one, the request namespace must be equal to the operand namespace, we also don't copy ....
Fixes #
```release-note
```

Skip reconcile bindinfo when requestNamespaces less than 2

---

pkg/apis/operator/v1alpha1/operandbindinfo_types.go
pkg/controller/operandbindinfo/operandbindinfo_controller.go
pkg/controller/operandrequest/operandrequest_controller.go

Requeue OperandBindInfo controller when the secret or configmap isn't created yet.
Fixes #352 
```release-note
NONE
```

Requeue for bindinfo

---

deploy/crds/operator.ibm.com_v1alpha1_operandconfig_cr.yaml

We are deprecating platform header and it doesn't need to be created when the commonui operator is deployed
Fixes # https://github.ibm.com/ibmprivatecloud/roadmap/issues/37289
```release-note
```

Removing platform header from config

---

README.md
deploy/olm-catalog/operand-deployment-lifecycle-manager/1.2.0/operand-deployment-lifecycle-manager.v1.2.0.clusterserviceversion.yaml
pkg/controller/operandbindinfo/operandbindinfo_controller.go
pkg/controller/operandbindinfo/operandbindinfo_controller_test.go

Revert #349 
In the Cloudpak scenario, there is only one OperandRequest and common services are not in the same namespace with Cloud Paks which require the bindinfo to copy secret and/or configmap.
```release-note
NONE
```

Revert 349 for Cloud Pak use case

---

pkg/apis/operator/v1alpha1/operandrequest_types.go
pkg/controller/operandrequest/reconcile_operator.go

This PR prevent users request private operator from the out of namespace of operandRegistry.
Hold it unit we get the list of public and private operators
Fixes #337 
```release-note
NONE
```

Add a check for operator scope

---

pkg/controller/operandbindinfo/bindInfo_status.go

- Don't add the namespace of bindinfo
- Deduplicate the namespace
Fixes #
```release-note
NONE
```

Deduplicate namespace in the operandbindinfo status

---

pkg/controller/operandbindinfo/bindInfo_status.go
pkg/controller/operandbindinfo/operandbindinfo_controller.go

This PR is for fixing the issue in the operandbindinfo status.
Issue: there is an empty namespace in bindinfo cr
```
root@zhiwei1:~# oc -n ibm-common-services get operandbindinfo management-ingress -o yaml
kind: OperandBindInfo
metadata:
creationTimestamp: "2020-05-17T08:15:58Z"
generation: 2
labels:
ibm-common-services.common-service/registry: "true"
operator.ibm.com/opreq-control: "true"
name: management-ingress
namespace: ibm-common-services
resourceVersion: "2497030"
selfLink: /apis/operator.ibm.com/v1alpha1/namespaces/ibm-common-services/operandbindinfos/management-ingress
uid: a04fec8f-d07b-43ff-88f7-7953f4177071
spec:
bindings:
public:
configmap: ibmcloud-cluster-info
secret: ibmcloud-cluster-ca-cert …
```

update bindinfo status

---

pkg/controller/operandbindinfo/operandbindinfo_controller.go

It is a follow-up PR for the #390. It is to cover the case that there is an error when fetching the operandrequest. 
```release-note
NONE
```

continue the loop when can't get request

---

pkg/controller/operandregistry/operandregistry_controller.go
pkg/controller/operandrequest/operandrequest_controller.go
pkg/controller/operandrequest/reconcile_operator.go

This PR is for decoupling the OperandRegistry reconciliation with the OperandRegistry to avoid the race condition.
Then it can fix the deletion detects mentioned in #434 and #435.
Fixes #434 #435 
```release-note
NONE
```

Update operator deletion check

---

pkg/controller/operandrequest/reconcile_operand.go

Move the CSV status out of the getClusterServiceVersion function to unblock deleting the failed CSV.
Fixes #442
```release-note
```

Move csv status checking out of get csv function

---

pkg/controller/operandrequest/operandrequest_controller.go
pkg/controller/operandrequest/reconcile_operand.go
pkg/controller/operandrequest/reconcile_operator.go

1. Use multiErr when to delete sub, if one operator delete failed, it will not block other
2. Set operator status is Installing when the CSV phase is not succeeded.
Fixes #444 #445 
```release-note
```

Use multiErr when delete

---

pkg/apis/operator/v1alpha1/finalizer.go
pkg/apis/operator/v1alpha1/operandbindinfo_types.go
pkg/apis/operator/v1alpha1/operandconfig_types.go
pkg/apis/operator/v1alpha1/operandregistry_types.go
pkg/apis/operator/v1alpha1/operandrequest_types.go
pkg/controller/operandconfig/operandconfig_controller.go
pkg/controller/operandregistry/operandregistry_controller.go
pkg/controller/operandrequest/operandrequest_controller.go
pkg/controller/operandrequest/reconcile_operand.go

Fixes #395
This PR set finalized to OperandConfig and OperandRegistry, in case they are deleted by users accidentally before operandRequests are deleted.
```release-note
NONE
```

Add finalizers to operandRegistry and operandConfig

---

pkg/constant/constant.go
pkg/controller/operandrequest/operandrequest_controller.go
pkg/controller/operandrequest/operandrequest_controller_test.go
pkg/controller/operandrequest/reconcile_operand.go
pkg/controller/operandrequest/reconcile_operator.go

Add label to prevent subscription and CR uninstall
ODLM won't delete operators/CRs with label   "operator.ibm.com/opreq-do-not-uninstall: 'true'"
Fixes #457 
```release-note
```

Add label to prevent subscription and CR uninstall

---

pkg/controller/common/fetch.go
pkg/controller/operandrequest/reconcile_operand.go
pkg/controller/operandrequest/reconcile_operator.go

This PR Implement two main functions:
- Subscriptions (operators) generated from the OCP console use the operator package name as the subscription name.
ODLM will check if the subscription/operator deployed by OCP console, then it won't deploy the same operator in the same namespace.
- If the subscription deployed by OCP console has the label "operator.ibm.com/opreq-control", then ODLM should manage CRs for the operator.
Fixes #457  …

Check the operator generated from the OCP console

---

controllers/common/fetch.go

In this PR, the controller doesn't return errors when the installplan is failed, which won't block the uninstall when the installplan is failed.
Fixes #483 
```release-note
```

controller doesn't return error when the installplan is failed

---

api/v1alpha1/operandconfig_types.go
bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
deploy/olm-catalog/operand-deployment-lifecycle-manager/1.3.0/operand-deployment-lifecycle-manager.v1.3.0.clusterserviceversion.yaml

Add display name for the OperandConfig. Otherwise, there is no OperandConfig showing on the operator page.
Fixes #
```release-note
```

Add displayname for OperandConfig

---

Makefile
api/v1alpha1/operandregistry_types.go
api/v1alpha1/operandrequest_types.go
controllers/operandbindinfo_controller.go
controllers/operandbindinfo_controller_test.go
controllers/operandconfig_controller.go
controllers/operandconfig_controller_test.go
controllers/operandregistry_controller.go
controllers/operandregistry_controller_test.go
controllers/operandrequest_controller.go
controllers/operandrequest_controller_test.go
controllers/suite_test.go

This PR adds basic unit tests for OperandConfig OperandRegistry and OperandRequest controller.
Because ODLM depends on OLM, thus the unit test has limits on checking all the functions, we still need e2e test to cover more testing cases.
Fixes #
```release-note
```

Add unit test for controllers

---

controllers/operandconfig_controller.go
controllers/operandregistry_controller.go
controllers/operandrequest_controller.go
controllers/reconcile_operand.go
controllers/reconcile_operator.go

This PR adds retry for OperandConfig, OperandRegistry, OperandRequest status update.
This PR adds retry for operator's CR update.
Fixes #399 
```release-note
```

Avoid conflict when CR and status update

---

controllers/common/fetch.go
controllers/operandrequest_controller_test.go
controllers/reconcile_operator.go
controllers/testutil/test_data.go
go.mod

This reverts commit d92bc1b7841c0276c5a7688cb96702d3dcae97e8.
Fixes #
```release-note
```

Revert "enhance fetch csv method for delete (#507)"

---

bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
config/default/manager_auth_proxy_patch.yaml
config/manager/manager.yaml
deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operand-deployment-lifecycle-manager.v1.4.0.clusterserviceversion.yaml

Remove flag of `enable-leader-election` from command args in order to disable this function.
@chenzhiwei @DanielXLee @horis233 Please correct me if it is wrong.

disable leader election to avoid pod restarting

---

controllers/reconcile_operand.go

Previously removed because of the defect in IAM operator. now add it back again.
https://github.com/IBM/operand-deployment-lifecycle-manager/pull/449#discussion_r447274571
Fixes #534 
```release-note
```

Operator is Running only after CSV is Succeeded

---

Makefile
bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
config/rbac/kustomization.yaml
config/rbac/role.yaml
config/rbac/role_binding.yaml
controllers/constant/constant.go
controllers/k8sutil/cache.go
controllers/operandbindinfo_controller.go
controllers/operandconfig_controller.go
controllers/operandregistry_controller.go
controllers/operandrequest_controller.go
controllers/reconcile_operand.go
controllers/suite_test.go
controllers/util/get_env.go
controllers/util/get_env_test.go
deploy/olm-catalog/operand-deployment-lifecycle-manager/1.4.0/operand-deployment-lifecycle-manager.v1.4.0.clusterserviceversion.yaml
go.mod
go.sum
main.go

1. Shrink permissions for ODLM to make it can be deployed in one namespace with few cluster permission.
2. If “INSTALL_SCOPE” is “namespaced”, then create the special cache for ODLM: It will list and watch ODLM CRs from the cluster but only list and watch resource for the namespace of the ODLM operator.
3. Else, it will use a filtered cache to list and watch resource from the cluster scope with a filter to reduce the memory usage.
Fixes # …

Shrink permissions for ODLM

---

controllers/operandrequest_controller.go
controllers/reconcile_operand.go

update warning message when service can't be found in OperandConfig
Fixes #546 
```release-note
```

update warning message when service can't be found in OperandConfig

---

controllers/operandrequest_controller.go

remove namespace from nss when there is no operandrequest in that namespace
Fixes #
```release-note
```

remove namespace from nss when there is no operandrequest in that ns

---

.gitignore

Remove `crds` from `.gitignore` file to avoid travis test failed in case bundle.

remove crds from .gitignore

---

controllers/operandrequest_controller.go

only reconcile operandrequest CR when its spec update.
It helps to finish endless reconciliation when ODLM can't find operators from the operandregistry.
Fixes #
```release-note
```

only reconcile operandrequest when spec change

---

controllers/operandconfig/operandconfig_controller.go

When updating the status of the OperandConfig, ODLM will check the status of OperandRegistry to check if the operator has been deployed.
Only if the operator is deployed, ODLM will update the status of OperandConfig for the CRs from that operator. 
```release-note
```

operandconfig status update

---

api/v1alpha1/operandrequest_types.go
controllers/operandrequest/operandrequest_controller.go
controllers/operandrequest/reconcile_operand.go
controllers/operandrequest/reconcile_operator.go

1. Update the OperandRequest status when its OperandRegistries are not found.
2. Replace `TODO` contexts to background contexts.
Fixes #
```release-note
```

update operandrequest status when registry notfound

---

bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml

1. Remove the `replace` section as it is the origin of v3 channel.
2. Keep `olm.skipRange: `'>=1.2.0 <1.5.0'` as it supports upgrading from the version smaller than `1.5.0`

switch 1.5 to v3 channel

---

controllers/operandbindinfo/operandbindinfo_controller.go
controllers/operandbindinfo/operandbindinfo_controller_test.go
controllers/testutil/test_util.go
docs/design/operand-deployment-lifecycle-manager.md

If the key of the bindings map is prefixed with protected, it means the secret and/or configmap can only be shared if it is explicitly declared in the OperandRequest.
Fixes #
```release-note
```

feat: Support `protected` prefix in bindinfo.

---

controllers/operandbindinfo/operandbindinfo_controller.go

should check whether the operator is found before we get its namespace.
When pick the change in `release-1.4` after this one is merged.

handle that not found operator in operandregistry

---

controllers/operandrequest/reconcile_operand.go
controllers/operandrequest/reconcile_operator.go

Delete subscriptions in the same request simultaneously.
Delete CR from the same subscription simultaneously.
Fixes #625 
```release-note
```

feat: Delete resources in parallel

---

docs/design/comparison-to-olm.md

Generalizing the examples to not have specific operators to avoid confusion.

Generalize the dependency examples.

---

bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
config/e2e/manager/manager.yaml
config/manager/manager.yaml
controllers/util/util.go
main.go

We will create an another ConfigMap called `odlm-scope` to manage the scope for ODLM.
It includes `ControlNs` comparing with the previous `namespace-scope` ConfigMap. We will remove `ControlNs` from `common-service` NSS CR.
```
apiVersion: v1
data:
namespaces: placeholder
kind: ConfigMap
metadata:
name: odlm-scope
namespace: placeholder
```
Namespace-scope operator will have an additional CR called `nss-odlm-scope` to update the above ConfigMap, to make sure that scope of ODLM is in the valid namespaces.
```
apiVersion: operator.ibm.com/v1
kind: NamespaceScope
metadata:
name: nss-odlm-scope
namespace: placeholder
spec:
namespaceMembers:
- placeholder
configmapName: odlm-scope
restartLabels:
intent: projected-odlm
```
Therefore `WATCH_NAMESPACE` in the csv in ODLM will change to watch the …

fetch ODLM_SCOPE and cache ODLM CRs

---

controllers/constant/constant.go
controllers/operandrequest/operandrequest_controller_test.go
controllers/operandrequest/reconcile_operand.go
controllers/operandrequest/reconcile_operator.go
controllers/testutil/test_util.go
controllers/util/util.go

Issue: When one subscription can't be deleted, if will block the operandrequest forever.
Solution: Set a timeout 10 mins to the subscription deletion.
Fixes #651 
```release-note
```

fix: Add a timeout for deleting an operandrequest

---

controllers/constant/constant.go
controllers/namespacescope/namespacescope_controler_test.go
controllers/namespacescope/namespacescope_controller.go
controllers/testutil/test_util.go
go.mod
main.go

ODLM will add the namespace which are captured from the `Namespace` where Operator will be installed in `OperandRegistry` and `Namespace` of `OperandRequest` into both `nss-managedby-odlm` and `odlm-scope-managedby-odlm` NSS CRs.
On the other word, those two NSS CRs has the same `namespaceMember`
The first `nss-managedby-odlm` is used to control namespace-scope for individual CS operators.
The latter `odlm-scope-managedby-odlm` is used to control namespace-scope for ODLM.
Also those two NSS CRs will only take effect in on-prem Single CS instance case.
If the `odlmScopeEnable` is `true`, indicating the SaaS or om-prem multi instances case, `namespacescope_controller` will be disabled and above two CRs will not be generated. See details here …

Reconcile two NSS CRs managedby ODLM

---

Makefile
controllers/operandbindinfo/operandbindinfo_controller.go
controllers/operandrequest/operandrequest_controller.go
controllers/operandrequest/operandrequest_controller_test.go

using patch command to add and remove finalizers from OperandRequest and OperandBindInfo to avoid the issue "the object has been modified; please apply your changes to the latest version and try again"
Fixes #
```release-note
```

feat: use patch command to manage resources finalizers

---

.github/dependabot.yml
Dockerfile

This configures Dependabot (Github feature) to automatically create PRs
whenever a newer base image is available. This simplifies the process
of switching to a new base image after security patches are released.
Fixes #
```release-note
```

build: enable Dependabot to upgrade base images

---

controllers/operandbindinfo/operandbindinfo_controller.go

currently, delete zen instance, zen-tenant will not be removed from iam/management-ingress bindinfo's `requestNamespace`

fix requestNamespaces for iam/management-ingress bindinfo

---

api/v1alpha1/operandrequest_types.go
bundle/manifests/operator.ibm.com_operandrequests.yaml
config/crd/bases/operator.ibm.com_operandrequests.yaml

Preserve the unknown filed in `spec` section of CRs when it is created by `OperandRequest`

apply k8s PreserveUnknownFields into API

---

bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
config/manager/manager.yaml

fix: Make probe more loose

---

controllers/operandrequest/reconcile_operand.go
controllers/operandrequest/reconcile_operator.go

make operatorconfig optional

---

controllers/operandrequest/operandrequest_controller.go

Current logic makes the operator uninstall by console/cli reinstall immediately, which is not expected by all the users
Fixes #
```release-note
```

fix: Operator only reconciles when watched subscriptions are updated.

---

Makefile
api/v1alpha1/operandconfig_types.go
bundle/manifests/operator.ibm.com_operandconfigs.yaml
config/crd/bases/operator.ibm.com_operandconfigs.yaml

The previous design used `spec` section for the configuration of that specific resource.
But I am thinking that if we could make the resource creation more generic by using the `data` section instead of `spec`
Here is the example for `Job` resource:
Previously
```
kind: OperandConfig
metadata:
name: operandconfig
namespace: default
spec:
services:
- name: example-operator
spec:
example-operand:
some-spec-field: myvalue
resources:
-   kind: Job
name:  registry-key-generater
apiVersion: batch/v1
spec: ------------------- spec indicates the spec section in job, but other section could not be created
template:
metadata:
..         
```
Now
```
kind: OperandConfig
metadata:
name: operandconfig
namespace: default
spec: …
```

add API for creating CR by OperandConfig

---

controllers/operandrequest/reconcile_operand.go

Some k8s resources could not be updated after it is created. `Job` for example
Since we will overwrite the resources when it is forced to update. now the update logic will delete the resource and then create a new one.

update the logic for updating the k8s resourcces

---

controllers/operandconfig/operandconfig_controller.go

Currently we use `.` to distinguish different segments in one string, for example
```
batch/v1.Job
```
But it does not work on some long API versions, for example
```
rbac.authorization.k8s.io/v1.Role
```
Update to `@` to avoid the repeating characters inside each segment.

Update the string splitter in OperandConfig status

---

api/v1alpha1/operandconfig_types.go
api/v1alpha1/operandrequest_types.go
controllers/operandrequest/reconcile_operand.go

Taking `ibm-metering-operator` as an example, it is removed from `OperandRegistry` after upgrading to cd version. But it still stays in `OperandRequest`.
If the service is not found in `OperandRegistry`, we will update the status of `ibm-metering-operator` to `Not Found` in `OperandRequest`.
The overall status of `OperandRequest` remains as `Running` and will no longer be affected by the status of those deprecated services.
Example
```
members:
- name: ibm-cert-manager-operator
phase:
operandPhase: Running
operatorPhase: Running
- name: ibm-mongodb-operator
phase:
operandPhase: Running
operatorPhase: Running
- name: ibm-licensing-operator
phase:
operandPhase: Running
operatorPhase: Running
- name: ibm-metering-operator
phase:
operandPhase: Not Found
operatorPhase: Not Found
```

update status of deprecated service to not found

---

controllers/constant/constant.go
controllers/operatorchecker/operatorchecker_controller.go

operator recovery logic

---

controllers/operatorchecker/operatorchecker_controller.go

Make operator upgrade more robust and won't impact fresh install operator
Fixes #
```release-note
```

fix: add more restricted rule for operator upgrade

---

api/v1alpha1/operandrequest_types.go

Reverts IBM/operand-deployment-lifecycle-manager#796

Revert "fix: When operandrequest is empty then set OperandRequest to running …"

---

api/v1alpha1/operandrequest_types.go
controllers/operandrequest/reconcile_operand.go
controllers/operandrequest/reconcile_operator.go
controllers/util/util.go

When we deploy the same services from different OperandRegistries, the newer version(newer channel) of services will have higher priority and will be applied to the subscription.

add version compare for subscription channel

---

common/scripts/next-csv.sh

Signed-off-by: YCShen1010 <yuchen.shen@mail.utoronto.ca>
Now the version bump script `next-csv.sh` is supported on both `linux` and `mac`

update version bump script by using "sed"

---

common/scripts/next-csv.sh

Signed-off-by: YCShen1010 
Fixed a bug in next-csv.sh, and will keep `minKubeVersion` value unchanged

keep minkube version unchanged in version bump script

---

Makefile

remove quay image build support

---

api/v1alpha1/operandrequest_types.go
controllers/operandrequest/operandrequest_controller.go
controllers/operandrequest/reconcile_operand.go
controllers/operandrequest/reconcile_operator.go

ODLM get the operators which will be deleted by [comparing the differences](https://github.com/IBM/operand-deployment-lifecycle-manager/blob/2e39cfbddb9b3a3b7092e12fac37947ce2777026/controllers/operandrequest/reconcile_operator.go#L430) between operators in `OperandRequest` status with operators in `OperandRequest` spec.
At the end of each reconciliation, ODLM will [refresh the `OperandRequest` status](https://github.com/IBM/operand-deployment-lifecycle-manager/blob/2e39cfbddb9b3a3b7092e12fac37947ce2777026/controllers/operandrequest/reconcile_operator.go#L52) based on existing operators in `OperandRequest` status.
When we remove an operator from `OperandRequest` spec, it will be removed from `OperandRequest` status as well.
However, if the deletion of those operators hits an error, those …

reserve the status for operators which are still in deletion stage

---

Dockerfile
Makefile
common/scripts/artifactory_config_docker.sh

[future] new artifactory image endpoint (odlm)

---

Makefile
api/v1alpha1/operandregistry_types.go
api/v1alpha1/operandrequest_types.go
bundle/manifests/operator.ibm.com_operandregistries.yaml
config/crd/bases/operator.ibm.com_operandregistries.yaml
controllers/operandrequest/reconcile_operator.go
controllers/operator/manager.go
docs/design/operand-deployment-lifecycle-manager.md

Introducing new parameter `.spec.operators[*].supportStatus` in OperandRegistry
`supportStatus` is the support status for services.
- When SupportStatus is `continous`, operator is supported to be fresh deployed via OperandRequest from scratch.
- When SupportStatus is `maintained`, operator is not supported to be fresh deployed via OperandRequest, only upgrade and deletion are allowed.
- The default value is `continous`
```
- sourceNamespace: openshift-marketplace
supportStatus: maintained  <-------------------
channel: v3.23
sourceName: opencloud-operators
installPlanApproval: Automatic
name: ibm-platform-api-operator
packageName: ibm-platform-api-operator-app
scope: public
namespace: cs-2
```

add tombstone parameter in OperandRegistry

---

controllers/operandrequest/reconcile_operand.go

skip reconcile CR when it only exists in alm-example, not OperandConfig

---

controllers/operandrequest/reconcile_operand.go

1. Install existing `future` CatalogSource
2. Install CommonService which brings up ODLM
3. Remove `IBMLicensing` from OperandConfig. We do not want ODLM to create it.
```
kind: OperandConfig
metadata:
name: common-service
namespace: cp4i
spec:
services:
- name: ibm-licensing-operator
spec:
operandBindInfo: {}
```
5. Invoke an OperandRequest containing `ibm-licensing-operator`
```
metadata:
name: example-service
namespace: cp4i
spec:
requests:
- operands:
- name: ibm-licensing-operator
registry: common-service
```
6. OperandRequest is failed due to `Failed` operandPhase for `ibm-licensing-operator`
```
- name: ibm-licensing-operator
phase:
operandPhase: Failed
operatorPhase: Running
phase: Failed
```
7. ODLM pod reports error msg …

[future] skip reconcile CR when it only exists in alm-example, not OperandConfig

---

controllers/operandrequest/reconcile_operator.go

We will have services marked as tombstone showing `Running` Status for both operator and operand
```
status:
members:
- name: ibm-cert-manager-operator
phase:
operandPhase: Running
operatorPhase: Running
phase: Running
```
Meanwhile, made some tradeoffs on `Conditions`, we will have no-op operators with
- the `Ready` condition to be `True`, showing `operator is ready`
```
status:
conditions:
- lastTransitionTime: '2023-02-15T20:39:28Z'
lastUpdateTime: '2023-02-15T20:39:28Z'
message: operator ibm-cert-manager-operator is ready
reason: operator is ready
status: 'True'
type: Ready
```
- the `NotFound` condition to be `Ture`, showing `operator is in maintenance status`
```
status:
conditions:
- lastTransitionTime: '2023-02-15T20:39:28Z'
lastUpdateTime: '2023-02-15T20:39:28Z'
message: …
```

update status for services marked as tombstone

---

api/v1alpha1/operandregistry_types.go
bundle/manifests/operator.ibm.com_operandregistries.yaml
common/config/.golangci.yml
config/crd/bases/operator.ibm.com_operandregistries.yaml
controllers/operandrequest/reconcile_operator.go
controllers/operator/manager.go
docs/design/operand-deployment-lifecycle-manager.md

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57399
- Since CP2 OperandRegistry CRD is not fully forward compatibility, `supportStatus` value from CP3 OperandRegistry will be pruned if an CP2 OperandRegistry CRD is applied in the cluster.
- As a result, we are not able to keep `supportStatus` parameter alive when there is CP3 instance installed, instead there is a new value `installMode:no-op` will be introduced to replace the functionality of `supportStatus` parameter.
- If `installMode:no-op`: operator is not supported to be fresh deployed via OperandRequest, only upgrade and deletion are allowed.
1. Firstly, install IBM foundational services 4.0 (Topology C with `cloudpak-control` and `cloudpak-data` ns), and there will be `supportStatus` description in OperandRegistry …

add new value no-op in installmode replace supportStatus

---

controllers/operandrequest/reconcile_operator.go

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57777
If there is an direct upgrade from `v3.22` to `v4.0` for Bedrock in AirGap env, to avoid the channels of those discontinued services being switched to `v3.23` by ODLM, and blocking upgrade, we are going to let ODLM not update operator/subscription if their subscription already exist

skip sub updating for discontinued services

---

controllers/operandrequest/reconcile_operator.go

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57978
Upgrade path: v3.22 -> v4.0, catalogsource has been updated to v4 catalogsource in `ibm-iam-operator` sub, even the channel in spec is still `v3.22`
**Case I** 
1. Test image: `quay.io/yuchen_shen/odlm:update_catalogsource`
2. `sub.Spec.source` will keep the old catalogsource 
**Case II**
1. try to change `im-operator` channel back to `v3.22` in opreg
2. apply test image and `sub.Spec.source` will updated to the new one

tolerate multi catalogsource for same service

---

api/v1alpha1/operandrequest_types.go
controllers/operandrequest/operandrequest_controller.go
controllers/operandrequest/reconcile_operand.go

Issue 58155 has found that ODLM may not instantiate status.services on first pass through for reconciling an operandrequest. This pr adds a check to see if status.service exists and to see if im is ready. If either of these checks fails, the operandrequest is requeued.
I have been testing the changes with a 4.0 deployment and so far so good. I'm going to try cleaning it up before merging as it's a little ugly compared to the other checks here.
Testing:
- install bedrock 4.0, just cs operator and odlm
- replace odlm image with this one (can build with makefile or ask me and I'll send you an image)
- create operand request with just im
- watch im operand request, make sure it is eventually (in a relatively short time frame) updated to include status.services
- watch odlm logs to see if it's …

check for status.services, im service status

---

api/v1alpha1/operandrequest_types.go
controllers/operandrequest/reconcile_operand.go
controllers/operandrequest/reconcile_operator.go

Previously, if an operator was removed from an operandrequest, its status.services entry would persist. This pr changes that and makes sure the entry is cleaned up on removal. I also addressed the iam/im naming issue and made a change that prevents indefinite reconciling for an operandrequest with im operator instead of iam.
To test:
- install cp3.0
- create operandrequest for im and mongodb (this creates a second opreq that also has mongodb)
- make sure the opreq has the mongo status.services entry
- remove mongodb from the original opreq
- give odlm a minute
- check the opreq again, verify status.services entry for mongodb no longer exists

Remove the status.services entry for an operator if it is removed from an operandrequest

---

bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml

for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/57411

odlm annotation updated for nss operator

---

controllers/operandbindinfo/operandbindinfo_controller.go

for ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/58807
An easier way to all multiple operandBindInfos mounting same secret
When two operandBindInfos are watching same secret/configmap, they are adding the same label to the secret/configmap ` operator.ibm.com/watched-by-opbi-with-name: ibm-licensing-bindinfo` 
This pr will try to fix it by adding a number after the label key
test:
1. install cs-operator and odlm
2. create two operandBindInfos for Licensing configmaps and secrets
expect result:
1. operandBindInfo will not fail
2. configmaps and secrets will be copied to another namespace
3. there will be a new label in the secret `<namespace>.<name>/bindinfo: true`
This image can be used to verify `quay.io/yuchen_li1/odlm-amd64@sha256:ba111b9726675779bbdaafd6bfcbf583d6049d60 …

[LTSR] avoid OperandBindInfo label conflict

---

controllers/operandrequest/operandrequest_controller.go

At the end of each OperandRequest reconciliation, we will always try to patch OperandRequest status when this updated OperandRequest is different from original OperandRequest status obtained from the beginning of reconciliation.
However, it is possible that the latest OperandRequest in the cluster has a different status because ODLM will invoke `[.Status().Update` Request](https://github.com/IBM/operand-deployment-lifecycle-manager/blob/6450c266e85a1666399b39b8d27b974bb180196d/api/v1alpha1/operandrequest_types.go#L445)in the middle of reconciliation. And those updates are not recorded locally in operator cache.
In order to have the latest OperandRequest status is correctly reflected when ODLM tries to patch the status, we will always get the latest OperandRequest from cluster and then do …

Compare updated opreq status with latest opreq

---

go.mod
go.sum

go-restful package was included as a new dependency after last round of changes and it needs to be updated to address security vulnerabilities

update go-restful pkg for 3.19.14

---

controllers/operandconfig/operandconfig_controller.go
controllers/operandrequest/reconcile_operand.go

for issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59717
- Using `background cascading deletion` to clean up the jobs and its related pods
- Set `DeletePropagationBackground` to specify the propagation policy for the deletion, this policy indicates that the deletion should happen in the background, and it won't wait for dependent resources to be deleted first.
1. test image replaced in ODLM: quay.io/yuchen_shen/odlm:delete_job_pod
2. create single `cloud-native-postgresql-opreq` operandrequest, and waiting `postgresql-operator-controller-manager` and `create-postgres-license-config` two pods ready
3. delete `cloud-native-postgresql-opreq` operandrequest, will see two above pods are also deteled.
- [Garbage Collection](https://kubernetes.io/docs/concepts/architecture/garbage-c …

[4.2] delete Kubernetes resource with background propagation

---

bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
config/rbac/role.yaml
config/rbac/role_binding.yaml
controllers/operator/manager.go

for issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/54725
ODLM will prioritize CatalogSource for operator based on CatalogSource `.spec.priority` provided from OLM.
1. CatalogSources in the operator's namespace have a higher priority than those in other namespaces.
2. Within the same namespace, CatalogSources with higher priority values come first.
3. If both have the same namespace and priority, the CatalogSources are sorted based on their names in lexicographical order.
1. test image: quay.io/yuchen_shen/odlm:catalog_prority
2. create `ibm-operator-catalog` in `openshift-marketplace` ns and give `.spec.priority` to `10`,  and same time create `cloud-native-postgresql-catalog` 
3. will see in sub `cloud-native-postgresql`, the catalogsource is `ibm-operator-catalog` as …

[4.2] Sort Catalogsource by priority in ODLM

---

controllers/operandrequest/operandrequest_controller.go
controllers/operator/manager.go

Fix bug for missing operator ns when retrieving CatalogSource from packagemanifest to address the ODLM permission issue
issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60042
1. create keycloak operator in OperandReigstry without `namespace`
```
- channel: stable
installPlanApproval: Automatic
name: edb-keycloak
packageName: cloud-native-postgresql
scope: public
```
2. get pending status for keycloak operandrequest
```
status:
members:
- name: keycloak-operator
phase:
operandPhase: Not Found
operatorPhase: Not Found
phase: Pending
```
3. error msg in ODLM pod log
```
E0821 04:58:58.540533 1 reconcile_operator.go:87] Failed to get suitable OperandRegistry keycloak-simple/keycloak-registry: packagemanifests.packages.operators.coreos.com "cloud-native-postgresql" is forbidden: …
```

handle operator namespace could be optional in OperandRegistry

---

controllers/operandbindinfo/operandbindinfo_controller.go
controllers/operandconfig/operandconfig_controller.go
controllers/operandregistry/operandregistry_controller.go
controllers/operandrequest/operandrequest_controller.go
controllers/operator/manager.go

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60041
ODLM should be capable of concurrently reconciling two or more OperandRequests to unblock the Keycloak uninstallation process
1. Creates an OperandRequest requesting `keycloak-operator`
2. ODLM reconciles OperandRequest to create a new OperandRequest `edb-keycloak-request` to request `edb-keycloak`
3. ODLM reconcile OperandRequest `edb-keycloak-request` to create `edb-keycloak` operator and its operands.
4. Fail to uninstall the `keycloak-operator` even after deleting `keycloak-operator` from the OperandRequest and get error msg:
```
failed to reconcile Operators for OperandRequest keycloak/common-service: the following errors occurred:
- the following errors occurred:
- failed to delete k8s resource -- Kind: …
```

ODLM support concurrently reconciling multiple resources

---

api/v1alpha1/operandbindinfo_types.go
api/v1alpha1/operandconfig_types.go
api/v1alpha1/operandregistry_types.go
api/v1alpha1/operandrequest_types.go
bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
bundle/manifests/operator.ibm.com_operandbindinfos.yaml
bundle/manifests/operator.ibm.com_operandconfigs.yaml
bundle/manifests/operator.ibm.com_operandregistries.yaml
config/crd/bases/operator.ibm.com_operandbindinfos.yaml
config/crd/bases/operator.ibm.com_operandconfigs.yaml
config/crd/bases/operator.ibm.com_operandregistries.yaml
config/samples/kustomization.yaml
config/samples/operator_v1alpha1_operandbindinfo.yaml
controllers/operandrequest/operandrequest_controller.go

Fix validation error from operator-sdk
```
WARN[0000] Warning: Value operator.ibm.com/v1alpha1, Kind=OperandBindInfo: provided API should have an example annotation 
```

Add OperandBindinfo example into alm-example

---

bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml

Resolves https://github.ibm.com/IBMPrivateCloud/roadmap/issues/59790

Add the common label to operand Pod

---

bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
config/rbac/role.yaml

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60782
Explicitly listing out the basic permissions need by ODLM in its CSV to do reconciliation
resources list:  
- operandconfigs
- operandregistries
- operandrequests
- operandbindinfos
- configmaps
- secrets
- services
- routes
test image: quay.io/yuchen_shen/odlm:basic_permissions

list out basic permission needed by ODLM

---

bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
config/manager/manager.yaml
config/rbac/role.yaml

ODLM needs those additional permission after its wildcard permission is gone
- namespace
- operandrequest/status
- operatorgroup
- installplan
- keycloak
```
W1016 20:19:20.207113 1 reconcile_operator.go:296] failed to create the namespace cloudpak-data, please make sure it exists: namespaces is forbidden: User "system:serviceaccount:cloudpak-control:operand-deployment-lifecycle-manager" cannot create resource "namespaces" in API group "" at the cluster scope
...
W1016 19:52:37.601695    1 operandrequest_controller.go:121] No permission to update OperandRequest
...
E1016 20:04:23.080461       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v1.OperatorGroup: failed to list *v1.OperatorGroup: operatorgroups.operators.coreos.com is …
```

Add additional explicitly listed permission

---

bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
config/rbac/role.yaml

This fix is used to solve the permission error happened when createing ZenService:
```
E1019 18:51:37.406849 1 operandbindinfo_controller.go:202] failed to reconcile the OperandBindinfo nss-cp/ibm-zen-bindinfo: the following errors occurred:
- failed to create secret nss-cp/zen-ca-cert-secret: secrets "zen-ca-cert-secret" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
I1019 18:51:49.396182 1 operandrequest_controller.go:125] Reconciling OperandRequest: nss-cp/ibm-iam-service
```

add finalizers permission

---

controllers/operandrequest/reconcile_operand.go

This is used to address issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/60848
Previously, OperandRequest was set as the CONTROLLER of the resources created by OperandRequest.
When there are multiple OperandRequests the same resources. Only one of OperandRequest could be the controller.
```
apiVersion: operator.ibm.com/v3
kind: CommonService
metadata:
name: iaf-zen-test-cr
namespace: issue60848
ownerReferences:
- apiVersion: operator.ibm.com/v1alpha1
blockOwnerDeletion: true
controller: true          <------------- only one controller is allowed
name: example-service-2
uid: c12e3a0d-3ed3-470e-95b5-1534f23ee34f
labels:
operator.ibm.com/opreq-control: 'true'
spec:
size: starterset
```
The PR will set OperandRequest as the Owner of resources only. And k8s …

set OwnerReference for resources created by OperandRequest

---

Makefile
bundle.Dockerfile
bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
bundle/metadata/annotations.yaml
config/rbac/role.yaml

Fix the error found in SERT regression test which failed to install core services requested by OperandRequest, msg:
```
I1031 19:23:24.869269       1 operandrequest_controller.go:125] Reconciling OperandRequest: cp1-ns/common-service
I1031 19:23:24.869300       1 reconcile_operator.go:50] Reconciling Operators for OperandRequest: cp1-ns/common-service
E1031 19:23:24.897734       1 operandconfig_controller.go:85] failed to update the status for OperandConfig cs-data/common-service : packagemanifests.packages.operators.coreos.com "rhbk-operator" is forbidden: User "system:serviceaccount:cs-operators:operand-deployment-lifecycle-manager" cannot list resource "packagemanifests" in API group "packages.operators.coreos.com" in the namespace "cs-data"
E1031 19:23:24.951872       1 …
```

fix for failing to list packagemanifests resource

---

controllers/constant/constant.go
controllers/operandbindinfo/operandbindinfo_controller.go
controllers/operandrequest/operandrequest_controller.go
controllers/operandrequest/operandrequest_controller_test.go
controllers/operandrequest/reconcile_operand.go
controllers/operator/manager.go
controllers/testutil/test_util.go
controllers/util/util.go
go.mod
go.sum
main.go

**NOTE:** Basic test cases are added in this PR, and overall usage is illustrated below. I will create another PR to add more test cases and write complete doc.
ODLM OperandConfig supports to reference value from `ConfigMap`, `Secret` and other arbitrary objects.
`templatingValueFrom` is the top level key for the entire Templating Structure.
```yaml
image: 
templatingValueFrom:
default:
defaultValue: cp.icr.io/cp/cpd/edb-postgres-license-provider@sha256:2f302acebe51e10c5ddb24e425b70eebda3cd0cc1696a01e9aa1c51558da5f99
```
```yaml
image:  cp.icr.io/cp/cpd/edb-postgres-license-provider@sha256:2f302acebe51e10c5ddb24e425b70eebda3cd0cc1696a01e9aa1c51558da5f99
```
`configMapkeyRef` could be added under `templatingValueFrom` or `templatingValueFrom.default`
```yaml
apiVersion: v1
kind: ConfigMap …
```

Add value reference in OperandConfig

---

controllers/operandbindinfo/operandbindinfo_controller.go
controllers/operator/manager.go
controllers/util/util.go

Reuse the jsonpath parsing mechanism from [sharing Service info via OperandBindinfo](https://github.com/IBM/operand-deployment-lifecycle-manager/pull/993), to support jsonpath reference templating in OperandConfig.
How to test
- Deploy a daily CD build as usually in a simple topology mode.
- Update ODLM CSV to replace image to `quay.io/opencloudio/odlm:b94e8737-dirty` and update `ImagePullPolicy` to `Always`
- Deploy resources in the same namespace listed in the bottom
- Verify following object are created
- ConfigMap named `test-service-my-service`, this is created via OperandBindinfo, to convey the information directly obtained from service `my-service`
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
name: test-service-my-service
data:
world: 'https://my-service.yesy-jsonpath.svc:80' …
```

Support jsonpath in OperandConfig value reference

---

controllers/operandbindinfo/operandbindinfo_controller.go
controllers/operandrequest/reconcile_operand.go
controllers/util/util.go

This is used to address issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/61126
All the ConfigMaps and Secrets, which are copied by OperandBindinfo to the namespace where OperandRequest is located, will have OperandRequest as the OwnerReference.
Previously, OperandRequest was set as the CONTROLLER of those cm or secrets.
When there are multiple OperandRequests the same resources. Only one of OperandRequest could be the controller.
```
kind: Secret
apiVersion: v1
metadata:
name: keycloak-bindinfo-cs-keycloak-tls-secret
namespace: ibm-common-services
labels:
controller.cert-manager.io/fao: 'true'
ibm-common-services.keycloak-bindinfo/bindinfo: 'true'
operator.ibm.com/managedBy-opbi: copy
operator.ibm.com/referenced-by-odlm-resource: …
```

allow to add multiple owners to cm/secret

---

controllers/operandrequest/reconcile_operand.go
controllers/operandrequest/reconcile_operator.go
controllers/operator/manager.go

To address issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61390
Make several enhancements:
1. Increase the number of OperandRequests which could be reconciled by ODLM simultaneously to 10
2. Better Error handling to avoid removing operand from remainingOperands set, to keep track of failed uninstallation
3. In parent OperandRequest uninstallation reconciliation, skip waiting for its child OperandRequest to be deleted when this child OperandRequest is a "internal" OperandRequest as the operand of services.
- For example, `keycloak-operator` has a "internal" OperandRequest requesting `edb-keycloak` as the dependency of Keycloak operator.

Enhance error handling for uninstall procedure

---

Makefile
bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
version/version.go

For CPFS 4.4 release, only need to bump the version of ODLM and IM.

Bump ODLM to 4.2.3 for 4.4 release

---

controllers/operandrequest/reconcile_operand.go

When the label `operator.ibm.com/opreq-control: 'true'` for a resource is specified in OperandConfig, ODLM will always update this resources.
This is used to handle an upgrade scenario where the resource is previously not managed by ODLM, but it is managed by ODLM after upgrade.

Allow resources to be updated by ODLM when control label is specified

---

controllers/operator/manager.go

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61611
- Decrease the number of max concurrent reconciliation to 3, to avoid high CPU usage
- Use k8s Reader interface to get CSV from subscription, instead of Client interface. It avoids store all CSVs in the cache, to reduce memory usage in All Namespaces Mode.
```
> oc get csv -A | wc -l                                                    
1458
```
```
Every 2.0s: oc adm top pods -l name=operand-deployment-lifecycle-manager                                                                                                Daniels-MBP: Wed Jan 10 21:13:31 2024
NAME                                                    CPU(cores)   MEMORY(bytes)
operand-deployment-lifecycle-manager-6ff4db75ff-rp6zd   0m           264Mi
```
```
Every …
```

Reduce CPU and Memory usage

---

controllers/operator/manager.go

issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/62275
Add an additional layer on sorting the Catalog
1. CatalogSources in operator namespace (private CatalogSource) have a higher priority than those in other namespaces (global CatalogSource).
2. CatalogSources with higher `.spec.priority` values will be picked up first.
3. **CatalogSource that the cs-operator/odlm is already installed from would be picked up next, if it is in the list of CatalogSources for the operator we want to install**
- If this CatalogSource contains IM operator. i.e. `opencloud-operators`, it would be picked first instead of the `ibm-im-catalog` in lexicographical order.
- If this CatalogSource does not contain IM operator. i.e., `ibm-installer-catalog`, it would not even in the list of Catalog used for …

Prioritize the Catalog which ODLM is deployed from

---

controllers/operator/manager.go

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62214
Once Route `keycloak` is created by ODLM, and ODLM would revoke `Client.Get()` request to read the `host` from Route object. However, the Route object is instantly reconciled by openshift controller after it is created. As a result, Route Object stored in the ODLM's cache is outdated, and ODLM is not able to update it with error `the object has been modified; please apply your changes to the latest version and try again`
```
E0221 16:32:21.723501 1 manager.go:587] Failed to get value reference from Object 4-5-test/keycloak with path .spec.host: failed to update Route 4-5-test/keycloak: Operation cannot be fulfilled on routes.route.openshift.io "keycloak": the object has been modified; please apply your changes to the …
```

Read Object from k8s API directly instead of cache to avoid getting outdated object

---

controllers/operandbindinfo/operandbindinfo_controller.go

issue:  https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61333
When ODLM reconciles OperandBindinfo to copy ConfigMap/Secret to namespaces where the OperandRequests are located, it also counts the namespace that are being deleted. However, ODLM is not able to create any new ConfigMap/Secret in a namespace which is be terminating.
```
E1122 11:17:23.547665       1 operandbindinfo_controller.go:237] failed to reconcile the OperandBindinfo ibm-common-services/keycloak-bindinfo: the following errors occurred:
- failed to create ConfigMap cp4i-e2e-general-joy/cs-keycloak-service: configmaps "keycloak-bindinfo-cs-keycloak-service" is forbidden: unable to create new content in namespace cp4i-e2e-general-joy because it is being terminated
```
After applying the new image …

Skip OperandRequest for OperandBindinfo if the OperandRequest is in the deletion status

---

bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
config/rbac/role.yaml

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61103#issuecomment-74347408
Add `operator.ibm.com` cluster permission for ODLM to clean up resources

add CertManager and AuditLogging CR cluster permission to ODLM

---

Makefile
api/v1alpha1/operandconfig_types.go
bundle.Dockerfile
bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
bundle/manifests/operator.ibm.com_operandconfigs.yaml
bundle/metadata/annotations.yaml
config/crd/bases/operator.ibm.com_operandconfigs.yaml
config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
controllers/operandrequest/reconcile_operand.go
controllers/operandrequest/reconcile_operand_test.go
go.mod
go.sum

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61732
Introducing ability to specify OwnerReference for a object created by ODLM, here is the example in OperandConfig. It will set CR with kind `Keycloak` and name `cs-keycloak` as the owner of CR with kind `KeycloakRealmImport` and name `cs-cloudpak-realm`
```
resources:
- apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
name: cs-cloudpak-realm
force: false
ownerReferences:         <----------- new field
- apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
name: cs-keycloak
controller: false
- .... # second owner
data:
spec:
keycloakCRName: cs-keycloak
realm:
displayName: IBM Cloud Pak
```
- Apply OperandConfig CRD changes on the cluster, introducing OwnerReferences field, see file …

Introduce OwnReference API

---

controllers/operandrequest/reconcile_operand.go
controllers/util/merge.go

Issue: https://github.ibm.com/ibmprivatecloud/roadmap/issues/61283
For this enhancement, we allow users to perform additional customizations on Kubernetes resources created ODLM. ODLM will compare the existing Custom Resource in the cluster with the template in the OperandConfig, field by field. It will retain the fields that are not defined in OperandConfig instead of overwriting them.
Test image: quay.io/yuchen_shen/odlm:deep_merge
**resource: `keycloak-edb-cluster` Cluster CR**
Before apply the image 
- Remove `description` section under `.data.spec` for `keycloak-edb-cluster` service in OperandConfig, and restart ODLM pod, will observe the `description: EDB Database with IBM License Key` will be removed from Cluster CR
After apply the test image
- Add `description: EDB Database with …

Enable deep JSON merging for Kubernetes resources when updating them

---

controllers/operandrequest/reconcile_operand.go
go.mod
go.sum

Changed the deep copy library  in the existing code. This ensures proper deep copying functionality for slice types.
Updates for PR: https://github.com/IBM/operand-deployment-lifecycle-manager/pull/1019
Test image: quay.io/yuchen_shen/odlm:deep_merge

Update deepcopy library for any type deep copying

---

api/v1alpha1/operatorconfig_types.go
bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
bundle/manifests/operator.ibm.com_operatorconfigs.yaml
config/crd/bases/operator.ibm.com_operatorconfigs.yaml
config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
config/rbac/role.yaml

- Add OperandBindinfo permission explicitly back to RBAC
- Update the additional columns from CLI
```console
> oc get operatorconfig -n test-operator-config
NAME                                      AGE   PHASE   CREATED AT
cloud-native-postgresql-operator-config   23h           2024-04-03T04:00:26Z
```
- Remove additional space on display name

Improve UX experience for OperatorConfig

---

controllers/operator/manager.go
controllers/operatorconfig/operatorconfig_controller.go

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62886
- Fix ODLM crashing issue when the CSV for a subscription is not found.
```log
I0405 19:45:19.234024 1 operatorconfig_controller.go:94] ClusterServiceVersion for Operator edb-keycloak/cloud-native-postgresql not found
I0405 19:45:19.234185 1 operatorconfig_controller.go:65] Reconciling OperatorConfig for request: test-operator-config, example-service
W0405 19:45:19.683699 1 operandconfig_controller.go:158] ClusterServiceVersion for the Subscription test-operator-config/edb-keycloak doesn't exist, retry...
W0405 19:45:19.722368 1 operandconfig_controller.go:158] ClusterServiceVersion for the Subscription test-operator-config/edb-keycloak doesn't exist, retry...
```
- Use `continue` when the OperatorConfig CR is not found or …

Update OperatorConfig reconciliation and improve error handling

---

controllers/operandrequest/reconcile_operator.go

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/62726#issuecomment-77073414
Previously ODLM will **unconditionally** set the channel annotation for `no-op` operator the same as subscription spec. Here is [the reason why we are doing this initially, to avoid intermediate upgrade issue in Airgap ENV](https://github.com/IBM/operand-deployment-lifecycle-manager/pull/910)
But there is another case when there are OperandRequests requesting no-op `ibm-iam-operator` and new `ibm-im-operator`, ODLM sets channel annotation to `v4.5` for both OperandRequests.
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
annotations:
daily-cd.example-service-2.ibm-im-operator/request: v4.5     # new ibm-im-operator with v4.5 channel in OperandRegistry …
```

Set channel annotation for no-op equal to spec channel when spec channel is lower

---

controllers/util/merge.go

Issue: 
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63136
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63126
We've implemented JSON deep merge into ODLM reconciliation to support the merging of array objects. However, this  leads to a side effect where ODLM lost control over individual items in the arrays, causing problems during upgrades. This resulted in a case where the `ibm-iam-operator` in `ibm-bts-request` couldn't be removed and blocked the upgrade process.

Overwrite the array in deep merge logic

---

controllers/operatorconfig/operatorconfig_controller.go

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63295
Fix error when operator entry is not found in OperandRegistry
```
I0426 13:30:32.519386 1 reconcile_operator.go:50] Reconciling Operators for OperandRequest: navigator-ns/cp4i-navigator-pn-ibm-integration-platform-navigator
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd8 pc=0x15a74e9]
goroutine 1189 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:118 +0x1da
panic({0x17277e0?, 0x281ce30?}) …
```

Fix nil pointer issue when operator is not found in OperandRegistry

---

controllers/operandbindinfo/operandbindinfo_controller.go
controllers/operandrequest/operandrequest_controller.go
controllers/operandrequest/reconcile_operand.go
controllers/operandrequest/reconcile_operator.go
controllers/operator/manager.go
controllers/operatorconfig/operatorconfig_controller.go
controllers/util/merge.go

After comparing the logs in ODLM from CPFS 4.5 and 4.7 release, the main difference happened on `reconciling Operators for OperandRequest`. And the root cause is about [removing hardcode Catalog specified in the OperandRegistry](https://github.com/IBM/ibm-common-service-operator/pull/1802) for the adoption of Catalog separation.
After hardcode Catalog specified in OperandRegistry is removed, ODLM needs to do discovery for each operator in OperandRegistry, and find their available Catalog for installation. There are almost 50 operators in OperandRegistry, and it takes about 1 mins to find the Catalog for all of them.
However, from the operational perspective, ODLM does not have to find the CatalogSource for each operator in OperandRegistry since not …

Only discover catalog for an operator when it has been requested in OperandRequest

---

api/v1alpha1/operandrequest_types.go
controllers/operandrequest/operandrequest_controller.go
controllers/operandrequest/reconcile_operand.go

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63588#issuecomment-80838597
-  If the operator is not managed by ODLM, it will set the `operatorPhase` to `Failed` instead.
- Clean up the phase value of OperandRequest and of each operand member at the beginning of each opreq reconciliation.
image: quay.io/yuchen_shen/odlm:operand_phase
- Before applying the fix image:
- request `ibm-elasticsearch-operator`
- remove label and annotation in elasticsearch subscription:
```
operator.ibm.com/opreq-control: 'true'
cs-condition.example-service.ibm-elasticsearch-operator/request: v1.1
```
- obverse operand phase failed in OperandRequest, even there is no operand for elasticsearch 
```yaml
members:
- name: ibm-elasticsearch-operator
phase:
operandPhase: Failed
phase: Failed
```
- …

Fix operand phase error for Elasticsearch in OperandRequest

---

controllers/operator/manager.go

When operator is not found in OperandRegistry, `opt` is `nil` and there should be no catalog discovery for this `nil` object.
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63690#issuecomment-81218953
See comment https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63690#issuecomment-81222501

Skip catalog discover when operator is not found in OperandRegistry

---

controllers/constant/constant.go
controllers/operandrequest/reconcile_operand.go
controllers/operator/manager.go
controllers/operatorconfig/operatorconfig_controller.go
main.go

Reduce the k8s resource reconciliation time
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63499
ODLM will be capable of reconciling 3 resources(resource A, B, C) in parallel, to speed up the overall reconciliation time.
It is possible that the resource C depends on certain fields in resource A, so the reconciliation of resource C can't be completed until resource A is completed.
In order to minimize the waiting time, ODLM will always re-try the resource A reconciliation several times before raising an error. And the waiting time for each re-try is increased exponentially to avoid …

reconcile k8s resource in parallel and with retry logic

---

controllers/operandconfig/operandconfig_controller_test.go
controllers/operandregistry/operandregistry_controller_test.go
controllers/operandrequest/operandrequest_controller_test.go
controllers/operandrequest/reconcile_operator.go
controllers/operator/manager.go
controllers/testutil/test_util.go

Ensure that all CSVs tied to a subscription will be deleted when ODLM is deleting an operator.
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63676#issuecomment-81421553
After deleting the OperandRequest, ODLM will list the corresponding operator's CSV by labels, to ensure finding all the CSVs and delete it.
```logs
I0606 00:44:46.646520       1 operandrequest_controller.go:248] Deleting OperandRequest integration-quickstart-ibm-inte-6c1a-keycloak in the namespace test-upgrade
...
I0606 00:44:46.770573       1 reconcile_operator.go:439] Found 1 ClusterServiceVersions for Subscription test-upgrade/keycloak-operator
...
I0606 00:44:46.806260       1 operandrequest_controller.go:248] Deleting …
```

Find CSVs by label for an operator, to ensure deleting all the CSVs for a specific subscription

---

api/v1alpha1/operandrequest_types.go
controllers/constant/constant.go
controllers/operandrequest/operandrequest_controller.go
controllers/operandrequest/reconcile_operand.go

- Remove hardcoded `services` name, and use annotation in OperandRegistry for service status check. See details in PR https://github.com/IBM/ibm-common-service-operator/pull/2032
- Remove `ibm-iam-operator` from the service status check list given `ibm-iam-operator` represents CPFS v3 whose service status is not applicable.
- Move `members` status reset into `InitRequestStatus` status, and avoid unnecessary status update call to APIServer
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63673#issuecomment-81231213
Mainly the idea is to remove `ibm-iam-operator` from the service status …

Refactor members and services status update

---

controllers/operandrequest/reconcile_operand.go
controllers/operator/manager.go

In each reconciliation loop, ODLM will clean the CSV in service namespace when the CSV is redundant.
Usually a redundant CSV is created by OLM when ODLM is moving the operator subscription(ibm-events-operator) from service namespace(ibm-common-services) to operator namespace(openshift-operators), and OLM will still create redundant CSV for the old subscription in the service namespace even though the old subscription has been removed(it is due to OLM cache that is not been refreshed). Subsequently, redundant CSV is causing API overlap with new CSV in operator namespace. Please see details in [here](https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63676#issuecomment-81421553).
ODLM will identify one CSV as redundant when CSV does not have labels …

Clean redundant CSV in service ns during the migration

---

controllers/operandrequest/reconcile_operator.go
controllers/util/util.go
controllers/util/util_test.go

It is to enable the channel semantic version detection for EDB operator whose channel is `stable` or `stable-vX.Y`
- `stable` channel will be interpreted as version `v0.0.0`
- `stable-v1` channel will be interpreted as version `v1.0.0`
- `stable-v1.2` channel will be interpreted as version `v1.2.0`
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/63488

Find semantic versioning from channel

---

bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
config/e2e/manager/manager.yaml
config/manager/manager.yaml

add securityContext .ceccompProfile field to pod container
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64465

add securityContext .seccompProfile field

---

api/v1alpha1/operandregistry_types.go
bundle/manifests/operator.ibm.com_operandregistries.yaml
config/crd/bases/operator.ibm.com_operandregistries.yaml
controllers/operandbindinfo/operandbindinfo_suite_test.go
controllers/operandconfig/operandconfig_suite_test.go
controllers/operandregistry/operandregistry_suite_test.go
controllers/operandrequest/operandrequest_suite_test.go
controllers/operandrequest/reconcile_operand.go
controllers/operandrequest/reconcile_operator.go
controllers/operandrequest/reconcile_operator_test.go
controllers/operator/manager.go
controllers/operator/manager_test.go
controllers/operatorconfig/operatorconfig_suite_test.go
controllers/util/util.go
controllers/util/util_test.go

issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64549

implement channel fallback in catalog discovery

---

common/Makefile.common.mk
controllers/operandrequest/operandrequest_controller.go
controllers/operandrequest/reconcile_operator.go
controllers/operandrequest/reconcile_operator_test.go
controllers/operator/manager.go
controllers/testutil/packagemanifests_crd.yaml

fix issue on https://github.com/IBM/operand-deployment-lifecycle-manager/pull/1079#issuecomment-2320028445

Add packagemanifest CRD in test ENV

---

controllers/operandrequest/reconcile_operand.go
controllers/util/util.go

Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64018
This PR addresses the need to handle custom `spec.host` values for OpenShift Route resources when creating it. Specifically, if the resource is Route, the `spec.host value` is now dynamically read from the provided OperandConfig template. A hash of the `spec.host` value is then calculated and added to the resource's annotations. If the custom host is empty from Opcon, then the host value from the Route will be reverted back to default

Revert the host back to default value

---

controllers/operandrequest/operandrequest_controller.go
controllers/operandrequest/reconcile_operator.go

This fix will ensure that no duplicate subscriptions are created based on the same operator package name and different channels. Instead, if there are two OperandRequests with the same operator but different channels, ODLM will create only one subscription with the package name, as only one operator/subscription with a single channel is allowed to be installed in one tenant.
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64818
**Before/After fix in**
Request two same operator with diff channel
```
metadata:
name: example-service
spec:
requests:
- operands:
- name: cloud-native-postgresql-v1.22
- name: cloud-native-postgresql
registry: …
```

Use PackageName name as the name of subscription

---

controllers/constant/constant.go
controllers/operandrequest/reconcile_operand.go
controllers/util/merge.go
controllers/util/util.go

Related issues: 
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64018
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64893
- Every object created by ODLM adds a hash annotation, which is according to the template defined in OperandConfig.
- Introduced a hash-based comparison to determine whether updates are needed.
- For non-Job resources, the template is merged with the existing resource if the hashes match, ensuring new fields are added without overwriting unchanged ones. If the hashes don't match, the resource is overwritten by the template.
- Implemented a solution for deep merging resources, including metadata and spec, by using the merge functions.

Enhance ODLM create/update logic by adding hash values

---

api/v1alpha1/operandconfig_types.go
bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
bundle/manifests/operator.ibm.com_operandconfigs.yaml
config/crd/bases/operator.ibm.com_operandconfigs.yaml
config/rbac/role.yaml
controllers/operandrequest/operandrequest_controller.go
controllers/operandrequest/reconcile_operand.go
controllers/operandrequest/reconcile_operand_test.go
controllers/util/util.go
controllers/util/util_test.go

Please design details in https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64888#issuecomment-92166012
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64888
1. Install latest latest 4.6.x dev driver.
2. Patch ODLM CSV
- Latest image `quay.io/daniel_fan/odlm:88e3fddf-dirty`
- Change imagepullpolicy to `Always`
3. Add cluster permission in the cluster role `operand-deployment-lifecycle-manager`
```yaml
- apiGroups:
- apiextensions.k8s.io
resources:
- customresourcedefinitions
verbs:
- get
```
4.  Update OperandRegistry `common-service`, change `channel: stable-v22` for Keycloak 22 installation
```yaml
- channel: stable-v24   ---------> stable-v22
fallbackChannels:
- stable-v22
installPlanApproval: …
```

introduce api for optional fields in resource object

---

Dockerfile

Reverts IBM/operand-deployment-lifecycle-manager#1081
Looks like this build worked 2 weeks ago, but there is no ppc or s390 1.23.1-bullseye image now so builds are failing after the version bump. Reverting this temporarily until we can switch to bookworm.

Revert "build(deps): bump golang from 1.23.0-bullseye to 1.23.1-bullseye"

---

controllers/constant/constant.go
controllers/operandrequest/operandrequest_controller.go
controllers/operator/manager.go
controllers/util/util.go

What this PR does / why we need it:
k8s label name length limit to 64 characters, so olm will cut off any label longer than 64 characters
We rely on label to find csv and subscription, so we also need to cut of the label if it is longer than 64 characters.
Which issue(s) this PR fixes:
script enhancement for # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64378

label length limitation

---

controllers/operator/manager.go

ensure label within length limitation
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64378

ensure label within length limitation

---

controllers/operandrequest/reconcile_operand.go

To clean up the leftover Zen resource `meta-api-deploy` deployment, we added `operator.ibm.com/opreq-control: 'true'` to the Zen operator in the OperandConfig. Then, it could be deleted by checking if this label is present in the OperandConfig, rather than inspecting existing resources for this label. This approach is necessary because ODLM cannot apply the label to a v3 resource.
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/64488

Delete k8s resources by checking the label from OperandConfig

---

controllers/operandrequest/operandrequest_controller.go
controllers/operandrequest/reconcile_operator.go

When OperandRequest requests `cloud-native-postgresql` first, and request `cloud-native-postgresql-v1.22` later, both OperandRequest could be in `Running` status because `cloud-native-postgresql-v1.22` would tolerate `stable` channel from `cloud-native-postgresql`.
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65181
1. Install 4.6 dev build
2. Patch ODLM image `` in CSV and change imagePullPolicy to `Always`
3. Create two OperandRequets in sequence
```yaml
metadata:
name: edb-service-stable
spec:
requests:
- operands:
- name: cloud-native-postgresql
registry: common-service
---
metadata:
name: edb-service-stable-1-22
spec:
requests:
- operands:
- name: …
```

Tolerate both opt.channel and opt.FallbackChannels for one operator

---

controllers/operator/manager.go
controllers/operator/manager_test.go

Issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65336
Added permission check function to verify if it has the required permission, and then read catalog source by checking it before attempting to fetch them. If lacks permissions, limit catalog source processing to those in the operator namespace only.
Test image: quay.io/yuchen_shen/odlm:catalog_permission
**Case I:** Apply private CatalogSource for ODLM, IM and EDB
1. Install v4 operator and remove the catalog cluster permission for ODLM
2. IM and EDB could be installed successfully
**Case II:** Apply CatalogSource as usual in `openshift-marketplace`
1.  Install v4 operator and remove the catalog cluster permission for ODLM
2. Request to install IM, will get error msg 
```failed to reconcile Operators for OperandRequest …
```

Discover private CatalogSource only if no catalog cluster permission exists

---

controllers/operator/manager.go
controllers/operator/manager_test.go

1. ODLM will check its `get` permission on resource `catalogsources` in catalog namespace
- `hasCatalogPermission := m.CheckResAuth(ctx, pm.Status.CatalogSourceNamespace, "operators.coreos.com", "catalogsources", "get")`
2. ODLM will create object `SelfSubjectAccessReview` to validate its permission on certain resources
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65427
1. Deploy SC2 dev build with global catalog in `openshift-marketplace` namespace
2. Update ODLM CSV to update ImagePullPolicy to `Always`, change the verbosity from `-v=1` to `-v=2` and patch image …

Use SelfSubjectAccessReview to check ODLM's permission on getting catalog

---

controllers/operandrequest/operandrequest_controller.go
controllers/operandrequest/operandrequest_controller_test.go
controllers/operandrequest/reconcile_operand.go
controllers/operator/manager.go
controllers/testutil/test_util.go

We are updating the condition on triggering the reconciliation:
The reconciliation will be triggered as long as a ConfigMap or Secret with label `operator.ibm.com/watched-by-odlm: 'true'` is updated.
The reconciliation will be triggered when a ConfigMap or Secret with label `operator.ibm.com/watched-by-odlm: 'true'` is updated except the `ODLMWatchedLabel` label or `ODLMReferenceAnnotation` annotation.
- If the only update is about `ODLMWatchedLabel` or `ODLMReferenceAnnotation`, the reconciliation will not be triggered.
ODLM is adding `ODLMWatchedLabel` label and `ODLMReferenceAnnotation` annotation to any resources that it has reference on in OperandConfig. For example, ODLM is referring a ConfigMap named `openshift-service-ca.crt` in …

Check if Object is updated except certain label and annotations

---

bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml

..as defined in https://docs.redhat.com/en/documentation/red_hat_software_certification/2024/html-single/red_hat_openshift_software_certification_policy_guide/index#con-operator-requirements_openshift-sw-cert-policy-products-managed and required by RH Certification

add required OLM metadata

---

Makefile
api/v1alpha1/operandrequest_types.go
controllers/operandrequestnoolm/operandrequestnoolm_controller.go
controllers/operandrequestnoolm/reconcile_operand.go
controllers/operandrequestnoolm/reconcile_operator.go
controllers/operator/manager.go

**What this PR does / why we need it**: This PR enables ODLM to clean up operands and their resources when an operandrequest is deleted in a no olm scenario. I have tried to mirror or reuse as much as the regular olm-enabled process as possible so that it should be working mostly the same. The main difference is that instead of enabling all of this through subscription objects, it is now done through deployment and what I am referring to as a tracking configmap. @bitscuit and I discussed and we do not want to disrupt how ODLM handles knowing what to clean up too much by doing away with the annotation based tracking. However, we do not want these annotations to live in a resource controlled by helm (ie the deployment that is now the center piece of an operator) so we decided to create …

refactor no olm controller code to handle cleanup on operandrequest deletion

---

helm/templates/rbac.yaml

part of helm chart install debugging

specify operator namespace in rolebinding

---

controllers/operator/manager.go

Error handling for the case where the OperandRequest of an operator exists, but its deployment is missing in the cluster
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65885
Test image: `quay.io/yuchen_shen/odlm:no-deployment`
1. Create OperandRequest for `ibm-events-operator` and there is no events operator deployment in the cluster
**Before the fix, it will be panic error like:**
```
I0211 22:11:13.739803       1 reconcile_operand.go:95] Looking for deployment for the operator: ibm-events-operator
I0211 22:11:13.753482       1 manager.go:643] Get Deployment cloud-native-postgresql-operator with package name ibm-events-operator
I0211 22:11:13.753562       1 manager.go:643] Get Deployment ibm-common-service-operator with package name ibm-events-operator
I0211 …
```

Check deployment as pre-req and return error if missing

---

helm/templates/rbac.yaml

**What this PR does / why we need it**: Replacing https://github.com/IBM/operand-deployment-lifecycle-manager/pull/1123:
> PA is blocked by the ODLM role including wildcard permissions because they apply namespace scope charts via a tenant admin that has reduced permissions. To circumvent this problem, I have specifically included all resources mentioned in either alm-examples or operandconfig (as listed in the issue linked). I have also included pods because they are required to create the edb-license-role and daemonsets and statefulsets as ODLM was failing without them.
Fixes # …

replace wildcard with specific permissions

---

helm/templates/rbac.yaml
helm/values.yaml

**What this PR does / why we need it**: 
All charts created the operator's RBAC in all the namespaces for the tenant instead of namespace scope operator doing the permission projection.
**Slack discussion:** https://ibm-cloudplatform.slack.com/archives/C085K4TSJ5S/p1739389039395679
1. Running `helm template ./helm > tmp.yaml` to check if all the values passed in correctly
2. Apply the helm charts on OCP without NSS operator, and check if ODLM working properly.

Create all role and rolebindings in each namespace

---

helm/templates/rbac.yaml

**What this PR does / why we need it**: Replacing https://github.com/IBM/operand-deployment-lifecycle-manager/pull/1129. After removing wildcard permission in https://github.com/IBM/operand-deployment-lifecycle-manager/pull/1124, need to specify certain permissions. Noticed this permission was missing while testing BR
Fixes #
```release-note
```

add events permissions

---

controllers/operator/manager.go
controllers/operator/manager_test.go
controllers/util/util.go
docs/design/operand-deployment-lifecycle-manager.md

This enhancement added powerful conditional logic capabilities to the ODLM templating system, allowing for dynamic selection of values based on runtime conditions. The implementation supports both simple equality-based conditions and complex expressions with logical operators.
general ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66114
keycloak 26: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65922
1. Test image: quay.io/yuchen_shen/odlm:templating
2. Install keycloak 26+
3. Enable backchannel in OperandConfig Keycloak cr
```
data:
spec:
...
additionalOptions:                          <----- newly added
- name: hostname-backchannel-dynamic
value: "true"
...
...
proxy:
headers: xforwarded
features:
enabled:
- token-exchange
- admin-fine-grained-authz
```
and modify …

Add Conditional Logic Support to ODLM Templating System

---

controllers/operator/manager.go
controllers/operator/manager_test.go
controllers/util/util.go
docs/design/operand-deployment-lifecycle-manager.md

This enhancement added powerful conditional logic capabilities to the ODLM templating system, allowing for dynamic selection of values based on runtime conditions. The implementation supports both simple equality-based conditions and complex expressions with logical operators
cherry-pick: https://github.com/IBM/operand-deployment-lifecycle-manager/pull/1132
general ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66114
keycloak 26: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65922

Add Conditional Logic Support to ODLM Templating System (#1132)

---

controllers/operator/manager.go
controllers/operator/manager_test.go
controllers/util/util.go
docs/design/operand-deployment-lifecycle-manager.md

Added array and map support to the OperandConfig templating system, specifically in conditional branches. 
1. Array Support in Conditional Branches
Users can now define arrays of mixed item types in `then` and `else` branches. It can contain literals, ConfigMap references, Secret references, or Object references
2. Map Structure Support
Array items can include complex map structures with arbitrary key-value pairs
**Which issue(s) this PR fixes**
general ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66114
keycloak 26: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65922
**How to test:**
1. Test image: `quay.io/yuchen_shen/odlm:templating`
2. Install keycloak 26+
3. Apply cs image: `quay.io/yuchen_shen/cs_operator:hostnamev2` , …

Array enhancement for ODLM templating system

---

controllers/operator/manager.go

**What this PR does / why we need it**: Disable certain logging messages in no olm scenario as they are misleading and create a lot of noise in the ODLM logs when installing via helm chart.
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66009
```release-note
```

disable irrelevant logging messages that can be misleading

---

controllers/operator/manager.go
controllers/operator/manager_test.go
controllers/util/util.go
docs/design/operand-deployment-lifecycle-manager.md

Added array and map support to the OperandConfig templating system, specifically in conditional branches. 
cherry-pick: https://github.com/IBM/operand-deployment-lifecycle-manager/pull/1136
**Which issue(s) this PR fixes**
general ticket: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66114
keycloak 26: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/65922
**How to test:**
1. Test image: `quay.io/yuchen_shen/odlm:templating`
2. Install keycloak 26+
3. Apply cs image: `quay.io/yuchen_shen/cs_operator:hostnamev2` , which comes from [PR2347](https://github.com/IBM/ibm-common-service-operator/pull/2437)
4. Check if kc 26 is working

Array enhancement for ODLM templating system (#1136)

---

api/v1alpha1/operandconfig_types.go
api/v1alpha1/operandregistry_types.go
bundle/manifests/operator.ibm.com_operandregistries.yaml
config/crd/bases/operator.ibm.com_operandregistries.yaml
config/e2e/crd/bases/operator.ibm.com_operandregistries.yaml
controllers/operandconfig/operandconfig_controller.go
controllers/operandrequest/operandrequest_controller.go
controllers/operandrequest/reconcile_operand.go
controllers/operandrequest/reconcile_operator.go
controllers/operator/manager.go
test/e2e/helpers_test.go

Implement operator aliasing through the ConfigName field to allow multiple operator entries in OperandRegistry to share operand resources by pointing to the same configuration in OperandConfig.
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66289
1. Test image: quay.io/yuchen_shen/odlm:deletion
2. install `keycloak-operator` and then switch to `keycloak-operaot-v26`, all the keycloak resources will not be deleted

Add support for operator aliasing via ConfigName

---

api/v1alpha1/operandconfig_types.go
api/v1alpha1/operandregistry_types.go
bundle/manifests/operator.ibm.com_operandregistries.yaml
config/crd/bases/operator.ibm.com_operandregistries.yaml
config/e2e/crd/bases/operator.ibm.com_operandregistries.yaml
controllers/operandconfig/operandconfig_controller.go
controllers/operandrequest/operandrequest_controller.go
controllers/operandrequest/reconcile_operand.go
controllers/operandrequest/reconcile_operator.go
controllers/operandrequestnoolm/reconcile_operand.go
controllers/operandrequestnoolm/reconcile_operator.go
controllers/operator/manager.go
helm-cluster-scoped/templates/crd.yaml
test/e2e/helpers_test.go

Implement operator aliasing through the ConfigName field to allow multiple operator entries in OperandRegistry to share operand resources by pointing to the same configuration in OperandConfig.
Cherry-pick: https://github.com/IBM/operand-deployment-lifecycle-manager/pull/1141
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66289

[CD] Add support for operator aliasing via ConfigName (#1141)

---

controllers/operandbindinfo/operandbindinfo_controller.go

I am seeing issue that ODLM is crashed due to following error
```
fatal error: concurrent map iteration and map write
goroutine 1117 [running]:
github.com/IBM/operand-deployment-lifecycle-manager/v4/controllers/operandbindinfo.(*Reconciler).SetupWithManager.func2({{0x1c32118?, 0xc00248d900?}, {0x1c32118?, 0xc0017ffe00?}})
/workspace/controllers/operandbindinfo/operandbindinfo_controller.go:1059 +0x7f
sigs.k8s.io/controller-runtime/pkg/predicate.Funcs.Update(...)
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/predicate/predicate.go:88
sigs.k8s.io/controller-runtime/pkg/source/internal.EventHandler.OnUpdate({{0x1c1cd88, 0xc0001368a8}, {0x1c25830, 0xc0002aee80}, {0xc000e9fc40, 0x1, 0x1}}, {0x1965e80, 0xc00248d900}, {0x1965e80, ...}) …
```

Fix concurrent access issues by copying labels map in SetupWithManager

---

api/v1alpha1/operandrequest_types.go
controllers/operandrequest/operandrequest_controller.go
controllers/operandrequest/reconcile_operand.go
controllers/operandrequestnoolm/operandrequestnoolm_controller.go
controllers/operandrequestnoolm/reconcile_operand.go

Remove unnecessary API calls to update OperandRequest status in the middle of reconciliation. Instead the OperandRequest will only be updated at the end of reconciliation after all the status are collected.
This will reduce the k8s API workload, and reduce discrepancies introduced by status API calls between original instance and final reconciled instance.
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66283

Refactor service status update logic to remove unnecessary context and client parameters

---

bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
config/manager/manager.yaml
controllers/operandrequest/operandrequest_controller.go
helm/templates/operator-deployment.yaml

This is a PR to temporarily enable debug info for further ODLM debug in dev build. The debug verbosity should be decreased to 1 when we are approaching GA timeline.

Update manager verbosity level to 2 and add debug logging for reconciliation events

---

controllers/operandbindinfo/operandbindinfo_controller.go

When an object like configMap, secret watched by ODLM has an event happens, ODLM will receive this object event and trigger the OperandBindinfo reconciliation related to this Object.
For example, when ConfigMap `ibmcloud-cluster-info` is updated by IAM operator, ODLM would receive such configmap update event, and trigger OprandBindinfo `ibm-iam-bindinfo` reconciliation because ConfigMap `ibmcloud-cluster-info` contains Bindinfo related label `<ns>.ibm-iam-bindinfo/bindinfo: 'true'`.
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
name: ibmcloud-cluster-info
namespace: cd-daily
labels:
app: auth-idp
cd-daily.ibm-iam-bindinfo/bindinfo: 'true'
operator.ibm.com/managedBy-opbi: original
operator.ibm.com/watched-by-odlm: 'true'
data:
....
```
As an OperandBindinfo reconciliation result, ODLM …

Refactor Bindinfo controller logic on object event watching and reconciliation triggering condition

---

controllers/operandrequest/reconcile_operator.go
controllers/operandrequest/reconcile_operator_test.go

This PR fixes an issue where operands were unexpectedly deleted after upgrading from a CS pre-4.6.12 version to the latest one when Keycloak operators with shared config names were switched
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66421
1. Test image: quay.io/yuchen_shen/odlm:operand_deletion
2. **Case one**, fresh install CS 4.6.12, request `keycloak-operator`, switch the name to `keycloak-operator-v26` when all the pods for 24 are ready, and check if the keycloak CR is deleted and recreated. It should be kept.
3. **Case two**, fresh install pre-4.6.12 CS version, request `keycloak-operator`, upgrade CS to the latest SC2 version and using the test image for ODLM, and then …

Fix operand deletion inconsistency in Keycloak upgrade case

---

controllers/operandrequest/reconcile_operator.go
controllers/operandrequest/reconcile_operator_test.go

This PR fixes an issue where operands were unexpectedly deleted after upgrading from a CS pre-4.6.12 version to the latest one when Keycloak operators with shared config names were switched
Cherry-pick: https://github.com/IBM/operand-deployment-lifecycle-manager/pull/1151
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66421
1. Test image: quay.io/yuchen_shen/odlm:operand_deletion
2. **Case one**, fresh install CS 4.6.12, request `keycloak-operator`, switch the name to `keycloak-operator-v26` when all the pods for 24 are ready, and check if the keycloak CR is deleted and recreated. It should be kept.
3. **Case two**, fresh install pre-4.6.12 CS version, request `keycloak-operator`, …

[CD] Fix operand deletion inconsistency in Keycloak upgrade case

---

controllers/operator/manager.go
controllers/operator/manager_test.go
docs/design/operand-deployment-lifecycle-manager.md

Enhanced the `EvaluateExpression` function to properly handle Kubernetes resource quantities during value comparisons. Values with Kubernetes resource units (like Gi, Mi, Ki, m) were being compared correctly for now.
Cherry-pick: https://github.com/IBM/operand-deployment-lifecycle-manager/pull/1147
**Which issue(s) this PR fixes** :
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66114
**Examples**: 
Now correctly handles:
- Memory comparisons: "10Gi" > "2Gi"
- CPU comparisons: "2" > "1500m"
- Mixed unit comparisons: "1Gi" = "1024Mi"
- Different resource types: "100m" CPU ≠ "100Mi" memory
Test image: `quay.io/yuchen_shen/odlm:templating`

[CD] Enhance Kubernetes Resource Quantity Comparisons in Templating

---

Makefile
bundle/manifests/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
config/manifests/bases/operand-deployment-lifecycle-manager.clusterserviceversion.yaml
version/version.go

**What this PR does / why we need it**: Bump ODLM version for release 4.6.14

Bump ODLM to 4.3.13 for 4.6.14 release

---

controllers/operandbindinfo/operandbindinfo_controller.go

Some clients report IAM platform-xxx pods and usermgmt pod are restart every 2-5 hours in fresh installed environment. The `bindInfo/restartTime: <timestamp>` annotation matches the timestamp when pods are restarted. 
ODLM have a feature to watch some resources like secret, configmap, route and .... When those resource got update, ODLM will restart pods who mount those resource in their volume to trigger a reconciliation.
Then way of ODLM restart pods is adding an annotation `bindInfo/restartTime: <timestamp>` to pod deployment/statefulSet/daemonSet, and K8s will create a new pod to update this annotation.
For example, when secret `ibm-iam-bindinfo-platform-auth-secret` update, ODLM will add an annotation `bindinfo/restartTime: 2025-4-22.1359` to `usermgmt` deployment (because usermgmt …

use Reader.Get to get resource in cluster

---

controllers/operator/manager.go
controllers/util/util.go

This change will enhance our templating system to properly handle boolean values, allowing Keycloak CR to correctly specify boolean fields as first-class citizens rather than just as strings
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66572
1. Test images
CS: quay.io/yuchen_shen/cs_operator:kc_warning
ODLM: quay.io/yuchen_shen/odlm:kc_warning
2. Install CS 4.6.14 and replaced by above images
3. Request a Keycloak 26 and check the `backchannelDynamic` is under `hostname` field and no warning msg

Support templating system to properly handle boolean values

---

controllers/operator/manager.go
controllers/util/util.go

This change will enhance our templating system to properly handle boolean values, allowing Keycloak CR to correctly specify boolean fields as first-class citizens rather than just as strings
Cherry-pick:https://github.com/IBM/operand-deployment-lifecycle-manager/pull/1162
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/66572
1. Test images
CS: quay.io/yuchen_shen/cs_operator:kc_warning
ODLM: quay.io/yuchen_shen/odlm:kc_warning
2. Install CS 4.6.14 and replaced by above images
3. Request a Keycloak 26 and check the `backchannelDynamic` is under `hostname` field and no warning msg

[CD] Support templating system to properly handle boolean values (#1162)

---

common/scripts/lint_go.sh
controllers/operator/manager.go

Originally when there are multiple fallback channels defined for one operator, ODLM will only fallback to the channel with maximum semantic version.
- For example, if `stable-v1.25` and `stable-v1.22` channel does not exist for Postgres Operator, Postgres operator could not be installed from `stable` channel although it is defined in `fallbackChannels`
```yaml
- channel: stable-v1.25
fallbackChannels:
- stable-v1.22
- stable
installPlanApproval: Automatic
name: common-service-postgresql
namespace: cd-daily
packageName: cloud-native-postgresql
scope: public
```
And we will observe following error messages
```
W0508 15:41:16.073399 1 manager.go:212] Not found PackageManifest cloud-native-postgresql in the namespace cs1 has channel stable-v1.25
E0508 …
```

Refactor fallback channel selection to sort by semantic version and find the first available channel

---

controllers/k8sutil/cache.go
controllers/operandrequest/operandrequest_controller.go
controllers/operandrequestnoolm/operandrequestnoolm_controller.go

1. Replace `ResourceVersionChangedPredicate` with `GenerationChangedPredicate` for OperandRequest controller.
- With `ResourceVersionChangedPredicate`, OperandRequest controller updates the status for OperandRequest at the end of reconciliation loop, which will updates the OperandRequest ResourceVersion as well. Thus, such updates will immediately trigger a next reconciliation.
- With `GenerationChangedPredicate`, only OperandRequest `.spec` changes will trigger the reconciliation, to help avoiding endless reconciliation for OperandRequest.
2. Use correct label `operator.ibm.com/bindinfoRefresh: enabled` to cache deployment, statesulSet and DaemonSet.
Fixes: …

Correct resource label for caching and use GenerationChangedPredicate for OperandRequest reconciliation triggering

---

helm/templates/rbac.yaml

**What this PR does / why we need it**: When testing the helm charts with the updated conditional labeling today, I saw a problem with the rbac.yaml. It is because of how variables are referenced from inside of a loop. This PR fixes this bug
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/67932

Update rbac yaml template due to error when using variables inside of loop
